export type NewsType = "announcement" | "event" | "guide" | "beta";

export type NewsItem = {
  id: string;
  title: string;
  date: string; // ISO date string, e.g. 2025-11-14
  type: NewsType;
  summary: string;
  officialUrl?: string;
  tags?: string[];
};

type OfficialNewsRow = [
  id: string,
  title: string,
  date: string,
  type: NewsType,
  officialUrl: string,
  summary: string,
];

// Source of truth: https://www.wherewindsmeetgame.com/news/index.html
// Keep this array in the same order as the official news index. The official
// site can pin items out of strict date order, so news pages should not sort it.
const officialNewsRows: OfficialNewsRow[] = [
  [
    "june-5-version-1-7-patch-notes",
    "1.7 Version Patch Notes: Optimizations and Bug Fixes (June 5, 2026)",
    "2026-06-05",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/529update.html",
    "Official June 5 Version 1.7 fixes: regional server availability, controller responsiveness, Imperial Palace quest text, mobile scene loading, Palace Oddities, Hexi Familiar Faces NPCs, event rewards, PS5 map visuals, Skill Theft access, and Grand Nuo Ritual stability.",
  ],
  [
    "unofficial-trading-illegal-items",
    "Announcement on Crackdown Against Unofficial Trading and Recovery of Illegal Items",
    "2026-05-19",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/519Announcement.html",
    "Pinned official notice warning players against unofficial trades, low-price gift scams, black-market activity, and item recovery tied to rule-breaking sellers.",
  ],
  [
    "may-27-patch-notes",
    "May 27 Patch Notes",
    "2026-05-28",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/527update.html",
    "Live maintenance update for May 28, 2026, covering the new Version 1.7 content window and temporary feature availability.",
  ],
  [
    "imperial-palace-version-1-7-overview",
    "[The Imperial Palace] Version 1.7 Update Overview",
    "2026-05-27",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/TheImperialPalace.html",
    "Official overview for Version 1.7 and The Imperial Palace update.",
  ],
  [
    "version-1-7-path-balance-adjustment-may-28",
    "Version 1.7 Path Balance Adjustment Announcement (May 28)",
    "2026-05-26",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/Adjustment528.html",
    "Balance optimization focused on underperforming Paths, core player pain points, and selected game-mode experience adjustments.",
  ],
  [
    "account-suspension-may-18-may-24-2026",
    "Where Winds Meet - Account Suspension Notice (May 18-May 24)",
    "2026-05-25",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/Banreport525.html",
    "Official enforcement notice covering unauthorized third-party tools, abnormal behavior, and fair-play penalties.",
  ],
  [
    "may-22-patch-notes-and-bug-fixes",
    "May 22 Patch Notes and Bug Fixes",
    "2026-05-22",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/522update.html",
    "Patch notes announcing Version 1.7 pre-download availability, Imperial Palace preparation, cross-server Arena matchmaking, and bug fixes.",
  ],
  [
    "account-suspension-may-11-may-18-2026",
    "Where Winds Meet - Account Suspension Notice (May 11-May 18)",
    "2026-05-18",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/Banreport518.html",
    "Official account-suspension notice for May 11-May 18 violations and anti-cheat enforcement.",
  ],
  [
    "may-15-patch-notes",
    "May 15 Patch Notes",
    "2026-05-15",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/515update.html",
    "Patch notes for the Sandstorm Tavern release and related gameplay updates.",
  ],
  [
    "anti-cheat-enforcement-pvp-may-12-2026",
    "Anti-Cheat Enforcement Update for PvP Gameplay",
    "2026-05-12",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/AntiCheat512.html",
    "Official PvP fair-play update explaining monitoring and action against violations that damage the competitive environment.",
  ],
  [
    "account-suspension-apr21-may10-2026",
    "Where Winds Meet - Account Suspension Notice (April 21-May 10)",
    "2026-05-11",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/Banreport511.html",
    "Official account-suspension notice covering the April 21-May 10 window.",
  ],
  [
    "may-8-optimizations-fixes",
    "May 8 Optimizations & Fixes",
    "2026-05-08",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/may6updateEN.html",
    "May 8 patch notes including a Lost Chapter: To Friends, to the End objective fix and other optimizations.",
  ],
  [
    "exchange-code-announcement-may-2026",
    "Exchange Code Announcement",
    "2026-05-03",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/20260503/42815_1298976.html",
    "Official update explaining that a batch of 30 recently leaked exchange codes was disabled.",
  ],
  [
    "dev-ama-hexi-qinchuan-2026",
    "DEV AMA Recap: The Journey Through Hexi",
    "2026-05-02",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/20260502/42815_1298917.html",
    "Developer AMA recap for the Hexi expansion arc, from Jade Gate Pass to Qinchuan.",
  ],
  [
    "qinchuan-card-exchange-event",
    "Step Into the Painted Seasons - Collect & Win in the Qinchuan Card Exchange Event!",
    "2026-04-30",
    "event",
    "https://www.wherewindsmeetgame.com/jm/activity/3sSEXf/3acWUV?lang=en&jm_track=web_en",
    "Official Qinchuan Card Exchange event page for collecting memory cards and sharing rewards.",
  ],
  [
    "april-30-optimizations-and-fixes",
    "April 30 Optimizations and Fixes",
    "2026-04-30",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/April30OptimizationsandFixesEN.html",
    "Latest Eastwind Pavilion improvements and fixes for the April 30 update window.",
  ],
  [
    "flows-of-dreams-version-1-6",
    "[Flows of Dreams] Version 1.6 Update Overview",
    "2026-04-30",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/FlowsOfDreamsEN.html",
    "Official overview for Version 1.6, Flows of Dreams.",
  ],
  [
    "april-30-gear-development-optimization",
    "April 30 Gear Development Optimization Overview",
    "2026-04-28",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/430update.html",
    "Gear-development optimization overview based on real-time data and player feedback.",
  ],
  [
    "april-30-arena-guild-war-optimization",
    "April 30 Update: Arena & Guild War Optimization Overview",
    "2026-04-27",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/PVP427.html",
    "Arena and Guild War optimization overview ahead of the journey to Qinchuan.",
  ],
  [
    "account-suspension-april-24-2026",
    "Where Winds Meet - Account Suspension Notice",
    "2026-04-24",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/Banreport424.html",
    "Official account-suspension notice for unauthorized tools and abnormal in-game behavior.",
  ],
  [
    "april-16-optimizations-and-fixes",
    "April 16 Optimizations and Fixes",
    "2026-04-15",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/416update.html",
    "Rolling maintenance update notice for April 16, 2026, with optimizations and fixes.",
  ],
  [
    "as-snow-falls-version-1-5",
    "[As Snow Falls] Version 1.5 Update Overview",
    "2026-04-01",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/AsSnowFalls.html",
    "Official overview for Version 1.5, As Snow Falls.",
  ],
  [
    "discord-goose-store",
    "Discord Goose Store is Live - Merch, Gift Cards & More!",
    "2026-03-25",
    "event",
    "https://www.wherewindsmeetgame.com/news/official/GooseStore.html",
    "Official Discord Goose Store announcement for earning Goose Feathers and redeeming rewards.",
  ],
  [
    "home-afar-version-1-4",
    "[Home Afar] Version 1.4 Update Overview",
    "2026-03-05",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/HomeAfar.html",
    "Official overview for the Version 1.4 update.",
  ],
  [
    "community-meetup-san-francisco-gdc-2026",
    "WWM Community Meetup - San Francisco (Post-GDC 2026)",
    "2026-02-25",
    "event",
    "https://www.wherewindsmeetgame.com/news/official/20260225/42815_1288006.html",
    "Invitation for a small group of wanderers to join the dev team for a San Francisco community meetup.",
  ],
  [
    "where-winds-meet-gearup",
    "Where Winds Meet x GearUP",
    "2026-02-10",
    "event",
    "https://www.wherewindsmeetgame.com/news/official/GearUp.html",
    "Official partnership announcement between GearUP Game Booster and Where Winds Meet.",
  ],
  [
    "springs-bliss-version-1-3",
    "[Spring's Bliss] Version 1.3 Update Overview",
    "2026-02-05",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/SpringsBliss.html",
    "Official overview for the Version 1.3 update.",
  ],
  [
    "version-1-2-jan8-bug-fixes-optimizations",
    "Version 1.2 (January 8th) Bug fixes and Optimizations",
    "2026-01-14",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/JAN8.html",
    "Version 1.2 bug fixes and optimizations covering Online Mode exploration, Quest Replay, Martial Arts Effects, Monthly Fund improvements, and QoL changes.",
  ],
  [
    "live-to-game-1-2-overview",
    "[Live to Game] Version 1.2 Update Overview",
    "2026-01-08",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/LivetoGame.html",
    "Official overview for Version 1.2, Live to Game, including maintenance details, new areas, events, and optimizations.",
  ],
  [
    "updates-game-installation-playstation-store",
    "Updates on Game Installation and PlayStation Store",
    "2025-12-12",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/1212notice.html",
    "Notice about reinstalling the official release build and PlayStation Store purchase/platform rules.",
  ],
  [
    "timeless-bonds-1-1-overview",
    "[Timeless Bonds] Version 1.1 Update Overview (December 12)",
    "2025-12-11",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/TimelessBonds.html",
    "Official overview for Version 1.1, Timeless Bonds.",
  ],
  [
    "mobile-launch-faq",
    "Mobile Launch FAQ",
    "2025-12-09",
    "guide",
    "https://www.wherewindsmeetgame.com/news/official/MobileFAQ.html",
    "Official mobile FAQ covering cross-progression, cross-play, difficulty, controls, and cutscene behavior.",
  ],
  [
    "closed-beta-lucky-draw",
    "Notice: Closed Beta Pre-Registration Lucky Draw Event",
    "2025-12-08",
    "event",
    "https://www.wherewindsmeetgame.com/news/official/luckydraw.html",
    "Lucky Draw reward notice and submission/linking deadline extension for closed beta participants.",
  ],
  [
    "account-suspension-dec-2025",
    "Where Winds Meet - Account Suspension for Violations",
    "2025-12-06",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/BanReport.html",
    "Official violation and account-suspension report after global launch.",
  ],
  [
    "hearts-unite-post-launch-letter",
    "Hearts Unite as the Winds Meet.",
    "2025-11-23",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/official/251123.html",
    "Post-launch developer letter covering stability, localization, online/solo latency, PS5 performance, and future improvements.",
  ],
  [
    "global-launch-event-rewards",
    "Wind's Welcome Gifts - Global Launch Events & Rewards",
    "2025-11-14",
    "event",
    "https://www.wherewindsmeetgame.com/news/official/GlobalLaunch/LaunchGifts.html",
    "Global launch events and rewards announcement featuring free appearances, accessories, emotes, and more.",
  ],
  [
    "global-launch-redefine-everything",
    "Redefine Everything - Where Winds Meet Global Launch",
    "2025-11-14",
    "announcement",
    "https://www.wherewindsmeetgame.com/news/official/GlobalLaunch/SeversLive.html",
    "Global launch announcement for November 14, 2025, at 22:00 UTC.",
  ],
  [
    "cross-progression-account-linking-guide",
    "Cross-Progression Account Linking Guide",
    "2025-11-10",
    "guide",
    "https://www.wherewindsmeetgame.com/news/official/GlobalLaunch/CrossPlatform.html",
    "Official guide for linking accounts across Steam, Epic Games, the official PC launcher, and PlayStation.",
  ],
  [
    "pc-launcher-installation-guide",
    "Where Winds Meet PC Launcher Installation Guide",
    "2025-11-03",
    "guide",
    "https://www.wherewindsmeetgame.com/news/official/GlobalLaunch/InstallGuide.html",
    "Official PC launcher installation guide and pre-download announcement.",
  ],
  [
    "bug-bounty-final-beta",
    "Bug Bounty - Final Beta",
    "2025-07-25",
    "beta",
    "https://www.wherewindsmeetgame.com/news/official/2025/bughunter.html",
    "Final Beta bug bounty event details for players testing Where Winds Meet.",
  ],
  [
    "beta-access-download-guide",
    "Beta Access & Download Guide",
    "2025-07-23",
    "beta",
    "https://www.wherewindsmeetgame.com/news/official/2025/installguide.html",
    "Official beta-code redemption and game download instructions.",
  ],
  [
    "final-test",
    "WhereWindsMeet - The Final Test",
    "2025-06-30",
    "beta",
    "https://www.wherewindsmeetgame.com/news/official/2025/thefinaltestEN.html",
    "Official Final Test announcement and signup prompt.",
  ],
];

export const newsItems: NewsItem[] = officialNewsRows.map(
  ([id, title, date, type, officialUrl, summary]) => ({
    id,
    title,
    date,
    type,
    officialUrl,
    summary,
  }),
);

export const latestNewsDate = newsItems.reduce(
  (latest, item) => (item.date > latest ? item.date : latest),
  newsItems[0]?.date ?? "2025-01-01",
);
