// Post-process the Next.js static export in ./out for Workers Static Assets.
//
// The previous OpenNext runtime answered `/<page>/` with a 308 to `/<page>`
// (Next.js trailingSlash=false). Static-assets html_handling would use 307, so
// we emit explicit 308 rules for every exported page and every legacy redirect
// source to keep status codes identical for crawlers.
import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";

const root = resolve(import.meta.dirname, "..");
const out = resolve(root, "out");
const redirectsPath = join(out, "_redirects");

assert.ok(existsSync(out), "Missing ./out. Run `npm run build:static` first.");
assert.ok(existsSync(join(out, "404.html")), "Static export must contain 404.html");
assert.ok(existsSync(join(out, "sitemap.xml")), "Static export must contain sitemap.xml");
assert.ok(existsSync(join(out, "robots.txt")), "Static export must contain robots.txt");

function walk(dir) {
  const files = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}

const ignoredPages = new Set(["/404", "/_not-found", "/index"]);
const pages = walk(out)
  .filter((file) => file.endsWith(".html"))
  .map((file) => "/" + relative(out, file).split(sep).join("/").replace(/\.html$/, ""))
  .filter((page) => !ignoredPages.has(page) && !page.startsWith("/_next/"))
  .sort();

const base = readFileSync(redirectsPath, "utf8").replace(/\n# --- generated by scripts\/postbuild-static\.mjs[\s\S]*$/, "").trimEnd();
const legacySources = base
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line && !line.startsWith("#"))
  .map((line) => line.split(/\s+/)[0]);

for (const source of legacySources) {
  assert.ok(!source.includes("*") && !source.includes(":"), `dynamic rule not expected: ${source}`);
}

const slashRules = [...new Set([...pages, ...legacySources])]
  .filter((path) => path !== "/")
  .map((path) => `${path}/ ${path} 308`);

const total = legacySources.length + slashRules.length;
assert.ok(total <= 2000, `_redirects static rule limit exceeded (${total} > 2000)`);

writeFileSync(
  redirectsPath,
  `${base}\n\n# --- generated by scripts/postbuild-static.mjs: trailing-slash 308s (Next.js parity) ---\n${slashRules.join("\n")}\n`,
);

console.log(`postbuild-static: ${pages.length} pages, ${legacySources.length} legacy redirects, ${slashRules.length} trailing-slash rules (${total}/2000 static rules).`);
