import Link from "next/link";
import CdnImage from "@/components/CdnImage";
import { HomeHubBacklink } from "@/components/HomeHubBacklink";
import { LiteYouTubeEmbed } from "@/components/LiteYouTubeEmbed";

export type IntentGuideLanguage = "en" | "vi" | "de";
export type IntentGuideKind =
  | "drunken-fist"
  | "gauntlets"
  | "reflection-temple"
  | "mystic-arts"
  | "how-to-fly"
  | "inner-ways"
  | "mohist-hill"
  | "divinecraft-dungeons"
  | "phasecycle"
  | "zenithstride"
  | "ephemeral-glory"
  | "mirkvale";

const prefix = { en: "", vi: "/vn", de: "/de" } as const;

type ExtraItem = { title: string; body: string };
type RelatedLink = { href: string; label: string };

type GuideCopy = {
  checked: string;
  title: string;
  intro: string;
  hero: string;
  heroAlt: string;
  videoId?: string;
  videoTitle?: string;
  stepsTitle: string;
  steps: string[];
  extraTitle?: string;
  extraItems?: ExtraItem[];
  blockerTitle: string;
  fixes: string[];
  evidence: string;
  officialLabel: string;
  officialUrl: string;
  serpLabel: string;
  serpUrl: string;
  relatedTitle: string;
  related: RelatedLink[];
};

const guides: Record<IntentGuideKind, Record<IntentGuideLanguage, GuideCopy>> = {
  "drunken-fist": {
    en: {
      checked: "Version 2.1.3 · September 3, 2026",
      title: "Where Winds Meet Drunken Fist Unlock Guide: Skystrike Gauntlets & Riven Twinblades",
      intro: "Drunken Fist is the Bamboocut - Draught path that landed on Global on September 3. The useful answer is a four-stop unlock: Gasping Cliff for Skystrike Gauntlets, Li Yangui for Riven Twinblades, then two Qinghe chests for the remaining Inner Ways.",
      hero: "/guides/drunken-fist/hero.jpg",
      heroAlt: "Moonlit riverside camp where a wandering martial artist drinks from a gourd beside a fire",
      videoId: "3_OMV6jjJtM",
      videoTitle: "How to get Drunken Fist weapons and Inner Ways",
      stepsTitle: "Unlock both weapons in order",
      steps: [
        "Teleport to Gasping Cliff in Hidden Mountain, face the river, and walk the shoreline counter-clockwise until you find an old man and children by a bonfire.",
        "Win his Martial Fellowship fight, then talk again to receive Skystrike Gauntlets and the gold Inner Way Eonpour.",
        "In Qinghe Verdant Wilds, speak with Li Yangui a few steps north of the Northern Vow Ruins Boundary Stone (Revisit if you already finished Echoes of Old Battles) to receive Riven Twinblades and Skyspeak.",
        "Finish The Promised Light, teleport to Scripture Hall, and open the chest for Mistwing. If Scripture Hall is missing, the quest is not done.",
        "Finish Palace of Annals / Lucky Seventeen access, enter the marked building, and open the chest for Volutefit.",
      ],
      extraTitle: "How the drunken state actually works",
      extraItems: [
        { title: "Binge Points and Inebriate", body: "Skills on this path build Binge Points. Filling the gauge enters Inebriate, then Inebriate - Deepdaze for the enhanced gauntlet and twinblade finishers." },
        { title: "Gauntlets vs Twinblades", body: "Skystrike Gauntlets drink from the gourd to recover the combat gauge and can call a falcon while drinking. Riven Twinblades convert a full gauge into a multi-hit aerial burst." },
        { title: "Do not confuse 2.0 Gauntlets", body: "The Version 2.0 Mohist Hill gauntlets are Bamboocut - Kite. Drunken Fist is a separate September 3 path. Use the Gauntlets page if you only want the shop unlock." },
      ],
      blockerTitle: "Common blockers",
      fixes: ["No old man at the river: you are in Qinghe, not Hidden Mountain / Gasping Cliff.", "Li Yangui has no new dialogue: finish Echoes of Old Battles, then choose Revisit.", "No Scripture Hall stone: complete The Promised Light first.", "Final chest missing: Palace of Annals must be cleared before the building opens."],
      evidence: "Unlock stops are cross-checked against current Global walkthroughs and Game8 Inner Way locations. Menu names can vary by client language. Official Version 2.1.3 lists Skystrike Gauntlets, Riven Twinblades, Eonpour, Skyspeak, Mistwing, and Volutefit.",
      officialLabel: "Official September 3 Version 2.1 overview",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Current unlock walkthrough",
      serpUrl: "https://quoramarketing.com/how-to-get-drunken-fist-bamboocut-draught-martial-arts-inner-ways-where-winds-meet/",
      relatedTitle: "Stay on the Version 2.1.3 path",
      related: [
        { href: "/guides/gauntlets", label: "2.0 Gauntlets (Mohist shop)" },
        { href: "/guides/inner-ways", label: "Inner Ways hub" },
        { href: "/guides/martial-arts-weapons", label: "All martial arts" },
        { href: "/guides/clouded-revelation", label: "Clouded Revelation" },
      ],
    },
    vi: {
      checked: "Version 2.1.3 · 3/9/2026",
      title: "Mở khóa Drunken Fist Where Winds Meet: Skystrike Gauntlets và Riven Twinblades",
      intro: "Drunken Fist là đường Bamboocut - Draught ra mắt Global ngày 3/9. Cần bốn điểm: Gasping Cliff lấy găng, Li Yangui lấy song đao, rồi hai rương Qinghe cho Inner Way còn lại.",
      hero: "/guides/drunken-fist/hero.jpg",
      heroAlt: "Bên sông đêm trăng, võ sư già uống hồ lô bên lửa trại",
      videoId: "3_OMV6jjJtM",
      videoTitle: "Video mở khóa Drunken Fist và Inner Ways",
      stepsTitle: "Mở cả hai vũ khí theo thứ tự",
      steps: [
        "Dịch chuyển Gasping Cliff ở Hidden Mountain, nhìn ra sông và đi dọc bờ ngược chiều kim đồng hồ đến ông già và trẻ em bên lửa.",
        "Thắng Martial Fellowship, nói chuyện lần nữa để nhận Skystrike Gauntlets và Inner Way vàng Eonpour.",
        "Tại Verdant Wilds, nói với Li Yangui phía bắc Northern Vow Ruins (Revisit nếu đã xong Echoes of Old Battles) để nhận Riven Twinblades và Skyspeak.",
        "Xong The Promised Light, tới Scripture Hall mở rương Mistwing.",
        "Xong Palace of Annals / Lucky Seventeen, vào nhà được đánh dấu mở rương Volutefit.",
      ],
      extraTitle: "Cơ chế say rượu",
      extraItems: [
        { title: "Binge Points", body: "Kỹ năng đường này tích Binge Points. Đầy thước sẽ vào Inebriate rồi Deepdaze." },
        { title: "Găng và song đao", body: "Găng uống hồ lô để hồi gauge; song đao đổi gauge đầy thành đòn trên không." },
        { title: "Khác găng 2.0", body: "Găng Mohist Hill Version 2.0 là Bamboocut - Kite, không phải Drunken Fist." },
      ],
      blockerTitle: "Hay bị kẹt",
      fixes: ["Không thấy ông già: sai vùng, cần Hidden Mountain / Gasping Cliff.", "Li Yangui không thoại mới: làm Echoes of Old Battles rồi Revisit.", "Thiếu Scripture Hall: chưa xong The Promised Light.", "Rương cuối: cần xong Palace of Annals."],
      evidence: "Đối chiếu walkthrough Global hiện tại và vị trí Inner Way trên Game8. Tên menu có thể khác theo ngôn ngữ client.",
      officialLabel: "Tổng quan official 3/9",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Hướng dẫn mở khóa hiện tại",
      serpUrl: "https://quoramarketing.com/how-to-get-drunken-fist-bamboocut-draught-martial-arts-inner-ways-where-winds-meet/",
      relatedTitle: "Tiếp Version 2.1.3",
      related: [
        { href: "/guides/gauntlets", label: "Găng 2.0" },
        { href: "/guides/inner-ways", label: "Inner Ways" },
        { href: "/guides/martial-arts-weapons", label: "Võ học" },
        { href: "/guides/clouded-revelation", label: "Clouded Revelation" },
      ],
    },
    de: {
      checked: "Version 2.1.3 · 3. September 2026",
      title: "Where Winds Meet Drunken Fist freischalten: Skystrike Gauntlets und Riven Twinblades",
      intro: "Drunken Fist ist der Bamboocut-Draught-Pfad vom 3. September. Vier Stops: Gasping Cliff für die Stulpen, Li Yangui für die Twinblades, danach zwei Qinghe-Truhen für die restlichen Inner Ways.",
      hero: "/guides/drunken-fist/hero.jpg",
      heroAlt: "Mondhelle Flusskampfstelle mit altem Martial Artist, Kürbisflasche und Lagerfeuer",
      videoId: "3_OMV6jjJtM",
      videoTitle: "Drunken Fist und Inner Ways freischalten",
      stepsTitle: "Beide Waffen in dieser Reihenfolge",
      steps: [
        "Teleport nach Gasping Cliff in Hidden Mountain, zum Fluss blicken und das Ufer gegen den Uhrzeigersinn entlanglaufen, bis der alte Mann mit Kindern am Feuer sitzt.",
        "Martial-Fellowship-Kampf gewinnen, erneut sprechen: Skystrike Gauntlets plus goldenes Inner Way Eonpour.",
        "In Qinghe bei Li Yangui nördlich von Northern Vow Ruins sprechen (Revisit nach Echoes of Old Battles) für Riven Twinblades und Skyspeak.",
        "The Promised Light abschließen, Scripture Hall öffnen, Truhe für Mistwing.",
        "Palace of Annals / Lucky Seventeen abschließen, markiertes Gebäude betreten, Truhe für Volutefit.",
      ],
      extraTitle: "Rausch-Mechanik",
      extraItems: [
        { title: "Binge Points", body: "Pfad-Skills füllen Binge Points. Volle Leiste = Inebriate, dann Deepdaze." },
        { title: "Stulpen vs. Twinblades", body: "Stulpen trinken aus dem Kürbis; Twinblades wandeln die volle Leiste in einen Luft-Burst." },
        { title: "Nicht die 2.0-Stulpen", body: "Die Mohist-Hill-Stulpen aus Version 2.0 gehören zu Bamboocut - Kite." },
      ],
      blockerTitle: "Typische Blocker",
      fixes: ["Kein alter Mann: falsche Region, Hidden Mountain / Gasping Cliff nötig.", "Li Yangui ohne neuen Dialog: Echoes of Old Battles, dann Revisit.", "Kein Scripture Hall: The Promised Light fehlt.", "Letzte Truhe: Palace of Annals muss klar sein."],
      evidence: "Freischaltstops gegen aktuelle Global-Walkthroughs und Game8-Inner-Way-Orte geprüft. Menünamen können je nach Clientsprache abweichen.",
      officialLabel: "Offizieller 3.-September-Überblick",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Aktueller Unlock-Walkthrough",
      serpUrl: "https://quoramarketing.com/how-to-get-drunken-fist-bamboocut-draught-martial-arts-inner-ways-where-winds-meet/",
      relatedTitle: "Weiter mit Version 2.1.3",
      related: [
        { href: "/guides/gauntlets", label: "2.0-Gauntlets" },
        { href: "/guides/inner-ways", label: "Inner Ways" },
        { href: "/guides/martial-arts-weapons", label: "Kampfkünste" },
        { href: "/guides/clouded-revelation", label: "Clouded Revelation" },
      ],
    },
  },
  gauntlets: {
    en: {
      checked: "Version 2.0 / 2.1 · shop unlock still live",
      title: "Where Winds Meet Gauntlets: How to Get the Mohist Hill Weapon",
      intro: "The original Gauntlets are the Version 2.0 Bamboocut - Kite weapon from the Mohist Hill shop. You do not need to join the sect. This is not the September 3 Drunken Fist / Skystrike Gauntlets path.",
      hero: "/guides/gauntlets/hero.jpg",
      heroAlt: "Ornate bronze fighting gauntlets beside a wine gourd on a lacquer table",
      videoId: "VNqQVSQ5JOQ",
      videoTitle: "Gauntlets unlock, Inner Ways, and loadout notes",
      stepsTitle: "Buy the 2.0 Gauntlets",
      steps: [
        "Open Sects from the main menu, then open the shop.",
        "Choose View other sects and select Mohist Hill. This works while you are sectless.",
        "Buy the Gauntlets martial art plus the PVE Inner Ways listed in the shop (commonly Empirical Edge and Celestial Vigor).",
        "Finish the Changeless Heart campaign if you still need the last Inner Way for the kit.",
        "If you wanted the drinking / Inebriate kit instead, leave this page and open the Drunken Fist guide.",
      ],
      extraTitle: "Which gauntlet search is this?",
      extraItems: [
        { title: "Bamboocut - Kite", body: "Version 2.0 Hidden Mountain weapon. Shop purchase, construction-sect flavour, pairs with Rope Dart in many PVE notes." },
        { title: "Bamboocut - Draught", body: "Version 2.1.3 Drunken Fist. Skystrike Gauntlets + Riven Twinblades, unlocked in the world, not the Mohist shop." },
      ],
      blockerTitle: "Shop not showing the weapon",
      fixes: ["Use View other sects; the Mohist shop is visible without joining.", "Update to Version 2.0 or later. Version 1.8 clients do not have Hidden Mountain goods.", "If the listing is Skystrike / Draught, you are on the drunken path, not this shop item."],
      evidence: "Shop route is a current creator walkthrough used because the official 2.0 letter names Gauntlets and Mohist Hill without a step-by-step menu. Distinguish Draught vs Kite using the Version 2.1.3 overview.",
      officialLabel: "Official Hidden Mountain / Version 2.0 letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Gauntlets video walkthrough",
      serpUrl: "https://www.youtube.com/watch?v=VNqQVSQ5JOQ",
      relatedTitle: "Related weapon pages",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist unlock" },
        { href: "/guides/mohist-hill", label: "Mohist Hill sect" },
        { href: "/guides/weapons", label: "Weapon encyclopedia" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    vi: {
      checked: "Version 2.0 / 2.1 · shop vẫn mở",
      title: "Gauntlets Where Winds Meet: mua vũ khí Mohist Hill",
      intro: "Găng gốc là vũ khí Bamboocut - Kite Version 2.0 trong shop Mohist Hill. Không cần nhập môn. Đây không phải Skystrike Gauntlets của Drunken Fist ngày 3/9.",
      hero: "/guides/gauntlets/hero.jpg",
      heroAlt: "Găng đồng và hồ lô rượu trên bàn sơn mài",
      videoId: "VNqQVSQ5JOQ",
      videoTitle: "Video mở khóa Gauntlets",
      stepsTitle: "Mua găng 2.0",
      steps: [
        "Mở Sects, vào shop.",
        "View other sects → Mohist Hill. Vẫn được khi chưa nhập môn.",
        "Mua martial art Gauntlets và Inner Way PVE trong shop.",
        "Làm Changeless Heart nếu còn thiếu Inner Way cuối.",
        "Nếu muốn bộ uống rượu / Inebriate, sang trang Drunken Fist.",
      ],
      extraTitle: "Hai loại găng",
      extraItems: [
        { title: "Bamboocut - Kite", body: "Vũ khí Hidden Mountain 2.0, mua shop." },
        { title: "Bamboocut - Draught", body: "Drunken Fist 2.1.3, mở trong thế giới." },
      ],
      blockerTitle: "Shop không hiện",
      fixes: ["Phải View other sects.", "Cần client 2.0+.", "Nếu thấy Skystrike / Draught thì đó là đường say rượu."],
      evidence: "Đường shop lấy từ walkthrough creator; thư official 2.0 chỉ nêu Gauntlets và Mohist Hill.",
      officialLabel: "Thư Hidden Mountain",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Video Gauntlets",
      serpUrl: "https://www.youtube.com/watch?v=VNqQVSQ5JOQ",
      relatedTitle: "Trang liên quan",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist" },
        { href: "/guides/mohist-hill", label: "Mohist Hill" },
        { href: "/guides/weapons", label: "Vũ khí" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    de: {
      checked: "Version 2.0 / 2.1 · Shop weiterhin live",
      title: "Where Winds Meet Gauntlets: Mohist-Hill-Waffe kaufen",
      intro: "Die ursprünglichen Gauntlets sind die Version-2.0-Waffe Bamboocut - Kite im Mohist-Hill-Shop. Sektenbeitritt ist nicht nötig. Das ist nicht der Drunken-Fist-Pfad vom 3. September.",
      hero: "/guides/gauntlets/hero.jpg",
      heroAlt: "Bronzene Kampfhandschuhe neben einer Weinflasche",
      videoId: "VNqQVSQ5JOQ",
      videoTitle: "Gauntlets-Freischaltung",
      stepsTitle: "2.0-Gauntlets kaufen",
      steps: [
        "Sects öffnen, dann den Shop.",
        "View other sects → Mohist Hill. Funktioniert auch ohne Sekte.",
        "Gauntlets-Martial-Art und die PVE-Inner-Ways kaufen.",
        "Changeless Heart abschließen, falls das letzte Inner Way fehlt.",
        "Für das Trink-/Inebriate-Set die Drunken-Fist-Seite öffnen.",
      ],
      extraTitle: "Zwei Stulpen-Suchen",
      extraItems: [
        { title: "Bamboocut - Kite", body: "Version-2.0-Shopwaffe." },
        { title: "Bamboocut - Draught", body: "Drunken Fist 2.1.3, Welt-Unlock." },
      ],
      blockerTitle: "Shop zeigt nichts",
      fixes: ["View other sects nutzen.", "Client 2.0+ nötig.", "Skystrike / Draught gehört zum Drunken-Fist-Pfad."],
      evidence: "Shop-Route aus aktuellem Creator-Walkthrough; der offizielle 2.0-Brief nennt Gauntlets und Mohist Hill ohne Menüpfad.",
      officialLabel: "Offizieller Hidden-Mountain-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Gauntlets-Video",
      serpUrl: "https://www.youtube.com/watch?v=VNqQVSQ5JOQ",
      relatedTitle: "Weiter",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist" },
        { href: "/guides/mohist-hill", label: "Mohist Hill" },
        { href: "/guides/weapons", label: "Waffen" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
  },
  "reflection-temple": {
    en: {
      checked: "Event window · August 27 to September 27, 2026",
      title: "Where Winds Meet Reflection Temple Event Guide",
      intro: "Reflection Temple is the Ghost Month limited stage. There is no overworld door to hunt: open the event page and press Go. Survival is not enough. You have to learn the temple taboos, read offerings and paper effigies, and finish the unfinished ritual.",
      hero: "/guides/reflection-temple/hero.jpg",
      heroAlt: "Lantern-lit abandoned water temple with paper effigies and altar offerings over a misty pool",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Official Heaven’s Threshold / 2.1 context trailer",
      stepsTitle: "Start and clear the event",
      steps: [
        "Open the in-game event menu, select Reflection Temple, and press Go. The client teleports you; searching Jiangnan on foot will not start it.",
        "Pick first-person or third-person POV when prompted. First-person is closer to the intended horror read; third-person is easier for offering hunts.",
        "Read the temple taboos before walking. Turning around, answering disembodied voices, or touching the wrong object can kill the run on purpose.",
        "Treat altar offerings, lanterns, and paper effigies as the puzzle language: quantity, arrangement, and whether a flame is lit are the clues.",
        "Some objectives require you to die or look into the water. If a run ends suddenly, reread the last taboo instead of assuming a bug.",
        "After the quest, replay from the event page for extra Soulbound Paper collection rewards before September 27, 4:59:59 UTC+8.",
      ],
      extraTitle: "What the official letter actually asks you to notice",
      extraItems: [
        { title: "Folk taboos", body: "The studio designed the stage around Ghost Month prohibitions. There is no clean safety manual; you assemble the rules from ruins, deaths, and notes." },
        { title: "Ritual, not just escape", body: "Offerings feed wandering spirits, lanterns guide them, paper effigies can be decoys or vessels. Completing the lingering ritual is the real clear condition." },
      ],
      blockerTitle: "Stuck or scared you broke it",
      fixes: ["No map pin: use the event page teleport.", "Looping deaths: stop interacting and reread the last posted taboo.", "Missing extra rewards: finish the event-page objectives, not only the inner quest.", "After September 27 the stage archives; keep this page as a recap, not a live timer."],
      evidence: "Unlock method and event dates are current Game8 / official overlap. Taboo and ritual language is from the August 29 developer letter. Exact offering coordinates vary by run and are not invented here.",
      officialLabel: "Official Ghost Month developer letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/829devletter.html",
      serpLabel: "Event dates and start route",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/617349",
      relatedTitle: "While the event is live",
      related: [
        { href: "/guides/clouded-revelation", label: "Version 2.1 hub" },
        { href: "/guides/codes", label: "Codes" },
        { href: "/news", label: "Official news" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    vi: {
      checked: "Sự kiện · 27/8–27/9/2026",
      title: "Sự kiện Reflection Temple Where Winds Meet",
      intro: "Reflection Temple là sân khấu Ghost Month. Không có cửa trên map: mở trang sự kiện rồi nhấn Go. Phải học kiêng kỵ, đọc lễ vật và hoàn tất nghi lễ.",
      hero: "/guides/reflection-temple/hero.jpg",
      heroAlt: "Đền nước bỏ hoang, đèn lồng và hình nhân giấy",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Trailer official 2.1",
      stepsTitle: "Bắt đầu và clear",
      steps: [
        "Mở menu sự kiện, chọn Reflection Temple, nhấn Go.",
        "Chọn POV ngôi thứ nhất hoặc thứ ba.",
        "Đọc kiêng kỵ trước khi đi. Quay đầu, trả lời tiếng gọi, chạm sai vật có thể chết.",
        "Lễ vật, đèn, hình nhân giấy là ngôn ngữ đố: số lượng, sắp xếp, lửa cháy.",
        "Một số bước bắt buộc chết hoặc nhìn xuống nước — đọc lại kiêng kỵ, đừng vội báo bug.",
        "Replay từ trang sự kiện để lấy Soulbound Paper trước 27/9 4:59:59 UTC+8.",
      ],
      extraTitle: "Thư official muốn bạn để ý",
      extraItems: [
        { title: "Kiêng kỵ", body: "Không có sổ an toàn. Luật được ghép từ đổ nát, cái chết và ghi chú." },
        { title: "Nghi lễ", body: "Clear thật sự là hoàn tất nghi lễ chưa xong, không chỉ sống sót." },
      ],
      blockerTitle: "Kẹt",
      fixes: ["Không pin: dùng teleport sự kiện.", "Chết lặp: đọc lại kiêng kỵ.", "Thiếu quà: làm objective trang sự kiện.", "Sau 27/9 sự kiện lưu trữ."],
      evidence: "Cách vào và ngày sự kiện từ Game8/official. Ngôn ngữ kiêng kỵ từ thư 29/8.",
      officialLabel: "Thư Ghost Month",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/829devletter.html",
      serpLabel: "Ngày sự kiện",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/617349",
      relatedTitle: "Trong thời gian sự kiện",
      related: [
        { href: "/guides/clouded-revelation", label: "Version 2.1" },
        { href: "/guides/codes", label: "Code" },
        { href: "/news", label: "Tin tức" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    de: {
      checked: "Event · 27. August bis 27. September 2026",
      title: "Where Winds Meet Reflection Temple Event-Guide",
      intro: "Reflection Temple ist die Ghost-Month-Bühne. Es gibt keine Overworld-Tür: Eventseite öffnen und Go drücken. Du musst Tabus lernen, Opfergaben lesen und das offene Ritual beenden.",
      hero: "/guides/reflection-temple/hero.jpg",
      heroAlt: "Verlassener Wassertempel mit Laternen und Papierfiguren",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Offizieller 2.1-Trailer",
      stepsTitle: "Starten und abschließen",
      steps: [
        "Eventmenü → Reflection Temple → Go. Der Client teleportiert.",
        "First- oder Third-Person wählen.",
        "Tabus lesen, bevor du läufst. Umdrehen, Stimmen antworten oder falsche Objekte können den Run beenden.",
        "Opfergaben, Laternen und Papierfiguren sind die Puzzlesprache.",
        "Manche Ziele verlangen Tod oder Blick ins Wasser. Bei plötzlichem Ende das letzte Tabu neu lesen.",
        "Vom Eventmenü wiederholen für Soulbound Paper bis 27. September 4:59:59 UTC+8.",
      ],
      extraTitle: "Was der Entwicklerbrief betont",
      extraItems: [
        { title: "Tabus", body: "Es gibt kein Sicherheitshandbuch. Regeln entstehen aus Ruinen, Tod und Notizen." },
        { title: "Ritual", body: "Der echte Clear ist das unvollendete Ritual, nicht nur Überleben." },
      ],
      blockerTitle: "Hänger",
      fixes: ["Kein Pin: Event-Teleport.", "Todesschleife: Tabu neu lesen.", "Fehlende Extra-Rewards: Eventseiten-Ziele.", "Nach dem 27. September nur noch Archiv."],
      evidence: "Startweg und Daten aus Game8/Official. Tabu-Sprache aus dem Brief vom 29. August.",
      officialLabel: "Offizieller Ghost-Month-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/829devletter.html",
      serpLabel: "Eventdaten",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/617349",
      relatedTitle: "Während das Event läuft",
      related: [
        { href: "/guides/clouded-revelation", label: "Version 2.1" },
        { href: "/guides/codes", label: "Codes" },
        { href: "/news", label: "News" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
  },
  "mystic-arts": {
    en: {
      checked: "Evergreen unlock list · refreshed September 2026",
      title: "Where Winds Meet Mystic Arts: How to Equip and Unlock Them",
      intro: "Mystic Arts are the exploration-and-combat techniques on a separate wheel from weapon skills. Equip them in Develop, buy extra slots on the Talent track, then unlock the rest in the world. This page is the short list players actually search for.",
      hero: "/guides/mystic-arts/hero.jpg",
      heroAlt: "Wanderer performing a glowing mystic palm technique in a moonlit bamboo grove",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Official Hidden Mountain gameplay, including mystic movement",
      stepsTitle: "Equip and expand slots",
      steps: [
        "Open Develop from the menu wheel and select Mystic Arts to assign up to eight techniques.",
        "Hold R2 / RT (or the PC mystic key) to open the mystic wheel, then press a face button / 1-4.",
        "Buy extra slots on the Talent track with Talent Points from quests and open-world diversions. World Tier gates later slots.",
        "Passive arts such as Touch of Death do not need a wheel slot once unlocked.",
        "Flying arts still need the regional Afterglow Pendant. Use the How to Fly page for that gate.",
      ],
      extraTitle: "Highest-intent unlocks",
      extraItems: [
        { title: "Tai Chi", body: "Give the Qinghe Wayfarer Echo Jade, then learn from the bear. Throws enemies and breaks some hidden walls." },
        { title: "Cloud Steps", body: "Clear Tiger Fort under General’s Shrine. Combat head-bounce plus long out-of-combat leaps." },
        { title: "Touch of Death", body: "Finish Echoes of Old Battles at Battlecrest Slope. Passive stealth execution." },
        { title: "Meridian Touch", body: "Learn from Yan Qiren near Stonewash Strand in Verdant Wilds. Puzzle immobilize / heal tool." },
        { title: "Celestial Seize", body: "Complete Foul Play from Heaven’s Pier. Pull objects, steal, and power Mohist chain puzzles." },
        { title: "Free Morph", body: "Beat Tian Ying on campaign, then deflect spinning kicks on challenge. Dedicated page on this site." },
        { title: "Drunken Poet", body: "Keep drinking liquor from the Honest Merchant in Blissful Retreat / Harvestfall." },
        { title: "Meteor Flight", body: "Afterglow quest west of Moonveil Mountain, then Qinghe Exploration Level 4 pendant." },
      ],
      blockerTitle: "Why a mystic art will not equip",
      fixes: ["Slot still locked: spend Talent Points and raise World Tier.", "Flying does nothing: you have the art but not the regional pendant.", "Skill Theft failed: wait for the observation window and see the Skill Theft guide.", "Wrong wheel: weapon skills and mystic arts are separate hotbars."],
      evidence: "Equip/slot rules and the core location table follow VG247’s running list plus this site’s Free Morph and Skill Theft pages. Later Hidden Mountain arts should be checked in-game; this page does not invent unconfirmed drops.",
      officialLabel: "Official news trail",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Mystic Arts location table",
      serpUrl: "https://www.vg247.com/where-winds-meet-mystic-arts-guide-and-unlock-locations",
      relatedTitle: "Specialist mystic pages",
      related: [
        { href: "/guides/how-to-fly", label: "How to fly" },
        { href: "/guides/free-morph", label: "Free Morph" },
        { href: "/guides/skill-theft", label: "Skill Theft" },
        { href: "/guides/verdant-flute", label: "Verdant Flute" },
      ],
    },
    vi: {
      checked: "Danh sách thường trực · 9/2026",
      title: "Mystic Arts Where Winds Meet: trang bị và mở khóa",
      intro: "Mystic Arts nằm ở vòng kỹ năng riêng. Trang bị trong Develop, mua slot ở Talent, rồi mở trong thế giới.",
      hero: "/guides/mystic-arts/hero.jpg",
      heroAlt: "Lãng khách thi triển chưởng pháp phát sáng trong trúc lâm",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Gameplay official Hidden Mountain",
      stepsTitle: "Trang bị và mở slot",
      steps: [
        "Develop → Mystic Arts, gắn tối đa tám kỹ năng.",
        "Giữ R2/RT hoặc phím mystic, rồi bấm nút mặt / 1-4.",
        "Mua slot trên Talent track. World Tier khóa slot sau.",
        "Skill bị động như Touch of Death không cần slot.",
        "Kỹ năng bay cần Afterglow Pendant theo vùng — xem How to Fly.",
      ],
      extraTitle: "Mở khóa hay tìm nhất",
      extraItems: [
        { title: "Tai Chi", body: "Đưa Echo Jade cho Wayfarer Qinghe, học từ gấu." },
        { title: "Cloud Steps", body: "Clear Tiger Fort dưới General’s Shrine." },
        { title: "Touch of Death", body: "Xong Echoes of Old Battles." },
        { title: "Meridian Touch", body: "Yan Qiren gần Stonewash Strand." },
        { title: "Celestial Seize", body: "Foul Play ở Heaven’s Pier." },
        { title: "Free Morph", body: "Đánh Tian Ying rồi deflect kick ở challenge." },
        { title: "Drunken Poet", body: "Uống rượu Honest Merchant." },
        { title: "Meteor Flight", body: "Afterglow + Exploration Lv.4 Qinghe." },
      ],
      blockerTitle: "Không gắn được",
      fixes: ["Slot khóa: Talent Points / World Tier.", "Bay không được: thiếu pendant vùng.", "Skill Theft fail: xem trang Skill Theft.", "Nhầm vòng vũ khí và mystic."],
      evidence: "Bảng vị trí theo VG247 và các trang Free Morph / Skill Theft trên site.",
      officialLabel: "Tin official",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Bảng Mystic Arts",
      serpUrl: "https://www.vg247.com/where-winds-meet-mystic-arts-guide-and-unlock-locations",
      relatedTitle: "Trang chuyên",
      related: [
        { href: "/guides/how-to-fly", label: "Cách bay" },
        { href: "/guides/free-morph", label: "Free Morph" },
        { href: "/guides/skill-theft", label: "Skill Theft" },
        { href: "/guides/verdant-flute", label: "Verdant Flute" },
      ],
    },
    de: {
      checked: "Evergreen-Liste · September 2026",
      title: "Where Winds Meet Mystic Arts: ausrüsten und freischalten",
      intro: "Mystic Arts liegen auf einem eigenen Rad. Im Develop-Menü ausrüsten, Slots über Talente kaufen, den Rest in der Welt finden.",
      hero: "/guides/mystic-arts/hero.jpg",
      heroAlt: "Wanderer mit leuchtender Mystik-Technik im Bambushain",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Offizielles Hidden-Mountain-Gameplay",
      stepsTitle: "Ausrüsten und Slots",
      steps: [
        "Develop → Mystic Arts, bis zu acht Techniken.",
        "R2/RT halten, Gesichtstaste / 1-4.",
        "Weitere Slots auf dem Talent-Track. World Tier sperrt spätere Slots.",
        "Passive Künste wie Touch of Death brauchen keinen Slot.",
        "Flugkünste brauchen den regionalen Afterglow Pendant.",
      ],
      extraTitle: "Meistgesuchte Freischaltungen",
      extraItems: [
        { title: "Tai Chi", body: "Qinghe-Wayfarer Echo Jade geben, vom Bären lernen." },
        { title: "Cloud Steps", body: "Tiger Fort unter General’s Shrine." },
        { title: "Touch of Death", body: "Echoes of Old Battles." },
        { title: "Meridian Touch", body: "Yan Qiren nahe Stonewash Strand." },
        { title: "Celestial Seize", body: "Foul Play in Heaven’s Pier." },
        { title: "Free Morph", body: "Tian Ying, dann Kicks im Challenge-Modus deflecten." },
        { title: "Drunken Poet", body: "Schnaps beim Honest Merchant." },
        { title: "Meteor Flight", body: "Afterglow plus Qinghe Exploration 4." },
      ],
      blockerTitle: "Lässt sich nicht ausrüsten",
      fixes: ["Slot gesperrt: Talent Points / World Tier.", "Flug tot: regionales Pendant fehlt.", "Skill Theft fehlgeschlagen: eigene Seite.", "Falsches Rad: Waffe vs. Mystic."],
      evidence: "Slot-Regeln und Kernorte nach VG247 plus hiesige Free-Morph- und Skill-Theft-Seiten.",
      officialLabel: "Offizielle News",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Mystic-Arts-Tabelle",
      serpUrl: "https://www.vg247.com/where-winds-meet-mystic-arts-guide-and-unlock-locations",
      relatedTitle: "Spezialseiten",
      related: [
        { href: "/guides/how-to-fly", label: "Fliegen" },
        { href: "/guides/free-morph", label: "Free Morph" },
        { href: "/guides/skill-theft", label: "Skill Theft" },
        { href: "/guides/verdant-flute", label: "Verdant Flute" },
      ],
    },
  },
  "how-to-fly": {
    en: {
      checked: "Evergreen movement gate · September 2026",
      title: "Where Winds Meet How to Fly: Meteor Flight and Afterglow Pendant",
      intro: "Flying is a two-key unlock. The Afterglow quest west of Moonveil Mountain teaches Meteor Flight, but free flight stays locked until Qinghe Exploration Level 4 gives the Afterglow Pendant. Other regions repeat that pendant gate.",
      hero: "/guides/how-to-fly/hero.jpg",
      heroAlt: "Wanderer flying over misty mountain peaks with a spear trailing golden light",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Official footage of lightness movement in Hidden Mountain",
      stepsTitle: "Unlock free flight in Qinghe",
      steps: [
        "Find the fisherman by the pond west of Moonveil Mountain and start Afterglow.",
        "Clear the pond QTE, then the lake obstacle: triple-jump and aerial-dash across the jars without falling.",
        "Meteor Flight unlocks here, but it is still region-locked.",
        "Raise Qinghe Area Exploration to Level 4 via Oddities, Boundary Stones, chests, and quests. Claim the Afterglow Pendant from the exploration rewards screen.",
        "Return to the fisherman, show the pendant, and free flight stays available in Qinghe.",
        "Hold jump (Space / X / A) to launch, then time the on-screen jump prompts. Repeat exploration-level pendants in Kaifeng, Hexi, and Hidden Mountain.",
      ],
      extraTitle: "Other flying arts",
      extraItems: [
        { title: "Thousand-Mile Flight", body: "Often claimed from the Warrior’s Journey day-4 login track. Confirm the live reward row; it is not the same as Meteor Flight." },
        { title: "Fan Glider / Wind Rider", body: "Later lightness skills. They still obey the regional pendant rule." },
        { title: "Hidden Mountain verticality", body: "Version 2.1 mixes mystic movement with building and Cloudstair. Unlock the region first, then its exploration pendant." },
      ],
      blockerTitle: "I have the skill but I still cannot fly",
      fixes: ["No pendant: Exploration Level 4 is the real gate, not the Afterglow QTE.", "Wrong region: Qinghe pendant does not license Kaifeng.", "Hold jump on open ground; some interiors and no-coop zones block lightness.", "Check the map’s bottom-left exploration widget for the actual level."],
      evidence: "Quest route and pendant gate follow Dexerto’s current how-to-fly steps. Official 2.1 letters confirm lightness plus building as Hidden Mountain’s traversal theme without replacing the pendant rule.",
      officialLabel: "Version 2.1 developer letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "How to fly walkthrough",
      serpUrl: "https://www.dexerto.com/wikis/where-winds-meet/how-to-fly/",
      relatedTitle: "Movement and mystic links",
      related: [
        { href: "/guides/mystic-arts", label: "Mystic Arts" },
        { href: "/guides/new-players", label: "New players" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
        { href: "/tools/interactive-map", label: "Interactive map" },
      ],
    },
    vi: {
      checked: "Cổng di chuyển · 9/2026",
      title: "Cách bay Where Winds Meet: Meteor Flight và Afterglow Pendant",
      intro: "Bay gồm hai khóa. Afterglow dạy Meteor Flight, nhưng bay tự do cần Qinghe Exploration Lv.4 để lấy Afterglow Pendant.",
      hero: "/guides/how-to-fly/hero.jpg",
      heroAlt: "Lãng khách phi trên núi mây với thương vệt sáng",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Footage official Hidden Mountain",
      stepsTitle: "Mở bay tự do ở Qinghe",
      steps: [
        "Gặp ngư ông phía tây Moonveil Mountain, nhận Afterglow.",
        "Xong QTE ao và thử thách hồ: nhảy ba và dash trên chum.",
        "Meteor Flight mở nhưng vẫn khóa theo vùng.",
        "Đưa Qinghe Exploration lên Lv.4, nhận Afterglow Pendant.",
        "Quay lại ngư ông, đưa pendant.",
        "Giữ nhảy để cất cánh. Các vùng khác cần pendant riêng.",
      ],
      extraTitle: "Kỹ năng bay khác",
      extraItems: [
        { title: "Thousand-Mile Flight", body: "Thường lấy từ Warrior’s Journey ngày 4." },
        { title: "Fan Glider / Wind Rider", body: "Vẫn cần pendant vùng." },
        { title: "Hidden Mountain", body: "2.1 trộn mystic với xây Cloudstair." },
      ],
      blockerTitle: "Có skill vẫn không bay",
      fixes: ["Thiếu pendant Lv.4.", "Sai vùng.", "Trong nhà / no-coop zone.", "Xem widget exploration góc trái map."],
      evidence: "Tuyến quest theo Dexerto. Thư 2.1 xác nhận lightness nhưng không bỏ luật pendant.",
      officialLabel: "Thư Version 2.1",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "How to fly",
      serpUrl: "https://www.dexerto.com/wikis/where-winds-meet/how-to-fly/",
      relatedTitle: "Liên quan",
      related: [
        { href: "/guides/mystic-arts", label: "Mystic Arts" },
        { href: "/guides/new-players", label: "Tân thủ" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
        { href: "/tools/interactive-map", label: "Map" },
      ],
    },
    de: {
      checked: "Bewegungs-Gate · September 2026",
      title: "Where Winds Meet fliegen: Meteor Flight und Afterglow Pendant",
      intro: "Fliegen hat zwei Schlüssel. Afterglow westlich von Moonveil lehrt Meteor Flight, freies Fliegen braucht Qinghe Exploration Stufe 4 für das Afterglow Pendant.",
      hero: "/guides/how-to-fly/hero.jpg",
      heroAlt: "Wanderer fliegt über Nebelberge mit leuchtendem Speer",
      videoId: "pNjmMRlOXG4",
      videoTitle: "Offizielles Leichtkörper-Gameplay",
      stepsTitle: "Freies Fliegen in Qinghe",
      steps: [
        "Fischer westlich von Moonveil, Quest Afterglow.",
        "Teich-QTE und See-Hindernis mit Triple-Jump und Aerial-Dash.",
        "Meteor Flight ist noch regiongesperrt.",
        "Qinghe Exploration auf Stufe 4, Afterglow Pendant abholen.",
        "Pendant dem Fischer zeigen.",
        "Sprung halten zum Start. Andere Regionen brauchen eigene Pendants.",
      ],
      extraTitle: "Weitere Flugkünste",
      extraItems: [
        { title: "Thousand-Mile Flight", body: "Oft Tag-4-Login in Warrior’s Journey." },
        { title: "Fan Glider / Wind Rider", body: "Weiterhin regionales Pendant." },
        { title: "Hidden Mountain", body: "2.1 mischt Mystik mit Cloudstair-Bau." },
      ],
      blockerTitle: "Skill da, Flug tot",
      fixes: ["Kein Pendant Stufe 4.", "Falsche Region.", "Innenräume / No-Coop.", "Exploration-Widget unten links auf der Karte."],
      evidence: "Questroute nach Dexerto. 2.1-Briefe bestätigen Leichtkörper, ersetzen die Pendant-Regel nicht.",
      officialLabel: "Version-2.1-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "How-to-fly",
      serpUrl: "https://www.dexerto.com/wikis/where-winds-meet/how-to-fly/",
      relatedTitle: "Weiter",
      related: [
        { href: "/guides/mystic-arts", label: "Mystic Arts" },
        { href: "/guides/new-players", label: "Einsteiger" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
        { href: "/tools/interactive-map", label: "Karte" },
      ],
    },
  },
  "inner-ways": {
    en: {
      checked: "Version 2.1.3 Inner Ways · September 3, 2026",
      title: "Where Winds Meet Inner Ways: Equip Slots and the New Draught Set",
      intro: "Inner Ways are equippable passives. You comprehend a tome, then socket up to four. The September 3 path adds Eonpour, Skyspeak, Mistwing, and Volutefit for Drunken Fist. This page is the socket rules plus those four locations, not a 48-row wiki dump.",
      hero: "/guides/inner-ways/hero.jpg",
      heroAlt: "Wanderer channeling mystic energy, used here as Inner Way cultivation art",
      videoId: "3_OMV6jjJtM",
      videoTitle: "New Draught Inner Way pickup route",
      stepsTitle: "Make an Inner Way actually work",
      steps: [
        "Obtain a tome from a quest, chest, trial, outpost, or event.",
        "Comprehend it in the Inner Way menu. Owning the book is not enough.",
        "Equip it into one of the four active slots. Unequipped Inner Ways do nothing.",
        "Upgrade later with Inner Way Notes. Version 2.1 lowered some conversion costs; check the live tooltip before spending.",
      ],
      extraTitle: "New Bamboocut - Draught Inner Ways",
      extraItems: [
        { title: "Eonpour (gold)", body: "Inebriate damage and Skystrike Deepdaze tools. Speak with Jiu Qiansiu east of Gasping Cliff after the Martial Fellowship, or follow the drunken-fist gauntlet stop." },
        { title: "Skyspeak", body: "Extends Deepdaze for Riven Twinblades. Li Yangui north of Northern Vow Ruins, Revisit." },
        { title: "Mistwing", body: "Penetration-focused Draught support. Scripture Hall chest after The Promised Light." },
        { title: "Volutefit", body: "Damage reduction during Winebound states. Chest after Palace of Annals / Lucky Seventeen access." },
      ],
      blockerTitle: "Comprehended but no effect",
      fixes: ["Not socketed in one of the four slots.", "Wrong path pairing: Draught Inner Ways want the drunken weapons.", "Old tooltip: re-open the pane after the September 3 update.", "Notes spent on the wrong rarity: gold vs purple tomes are separate."],
      evidence: "Socket rules match long-running wiki descriptions. The four new names and pickup points match Game8’s September 3 Inner Way list and the Drunken Fist unlock route.",
      officialLabel: "Official September 3 overview",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Inner Way list",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/564726",
      relatedTitle: "Build these with",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist unlock" },
        { href: "/guides/builds", label: "Builds" },
        { href: "/guides/martial-arts-weapons", label: "Martial arts" },
        { href: "/guides/gauntlets", label: "2.0 Gauntlets" },
      ],
    },
    vi: {
      checked: "Inner Ways 2.1.3 · 3/9/2026",
      title: "Inner Ways Where Winds Meet: slot và bộ Draught mới",
      intro: "Inner Ways là bị động. Comprehend rồi gắn tối đa bốn. Ngày 3/9 thêm Eonpour, Skyspeak, Mistwing, Volutefit.",
      hero: "/guides/inner-ways/hero.jpg",
      heroAlt: "Lãng khách vận công",
      videoId: "3_OMV6jjJtM",
      videoTitle: "Tuyến Inner Way Draught",
      stepsTitle: "Cho Inner Way chạy",
      steps: [
        "Lấy sách từ quest, rương, trial, outpost, sự kiện.",
        "Comprehend trong menu. Có sách chưa đủ.",
        "Gắn vào một trong bốn slot.",
        "Nâng bằng Inner Way Notes. Kiểm tra tooltip live.",
      ],
      extraTitle: "Bộ Bamboocut - Draught mới",
      extraItems: [
        { title: "Eonpour", body: "Gasping Cliff / Jiu Qiansiu." },
        { title: "Skyspeak", body: "Li Yangui, Northern Vow Ruins." },
        { title: "Mistwing", body: "Rương Scripture Hall." },
        { title: "Volutefit", body: "Rương sau Palace of Annals." },
      ],
      blockerTitle: "Comprehend rồi không hiệu lực",
      fixes: ["Chưa gắn slot.", "Sai path vũ khí.", "Tooltip cũ, mở lại sau patch 3/9.", "Nhầm rarity sách."],
      evidence: "Luật slot theo wiki lâu năm. Bốn Inner Way mới theo Game8 3/9.",
      officialLabel: "Tổng quan 3/9",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Danh sách Inner Way",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/564726",
      relatedTitle: "Dùng cùng",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist" },
        { href: "/guides/builds", label: "Build" },
        { href: "/guides/martial-arts-weapons", label: "Võ học" },
        { href: "/guides/gauntlets", label: "Găng 2.0" },
      ],
    },
    de: {
      checked: "Inner Ways 2.1.3 · 3. September 2026",
      title: "Where Winds Meet Inner Ways: Slots und das neue Draught-Set",
      intro: "Inner Ways sind Passive. Tome verstehen, dann maximal vier socketen. Am 3. September kommen Eonpour, Skyspeak, Mistwing und Volutefit.",
      hero: "/guides/inner-ways/hero.jpg",
      heroAlt: "Wanderer kanalisiert Qi",
      videoId: "3_OMV6jjJtM",
      videoTitle: "Draught-Inner-Way-Route",
      stepsTitle: "Damit es wirkt",
      steps: [
        "Tome aus Quest, Truhe, Trial, Outpost oder Event.",
        "Im Menü comprehendieren.",
        "In einen der vier Slots legen.",
        "Mit Inner Way Notes upgraden, Live-Tooltip prüfen.",
      ],
      extraTitle: "Neue Bamboocut-Draught-Inner-Ways",
      extraItems: [
        { title: "Eonpour", body: "Gasping Cliff / Jiu Qiansiu." },
        { title: "Skyspeak", body: "Li Yangui, Northern Vow Ruins." },
        { title: "Mistwing", body: "Truhe Scripture Hall." },
        { title: "Volutefit", body: "Truhe nach Palace of Annals." },
      ],
      blockerTitle: "Comprehendiert, kein Effekt",
      fixes: ["Nicht gesocket.", "Falscher Waffenpfad.", "Altes Tooltip nach dem 3. September.", "Falsche Tome-Rarität."],
      evidence: "Socket-Regeln laut langjährigem Wiki. Die vier neuen Namen nach Game8 vom 3. September.",
      officialLabel: "Überblick 3. September",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Inner-Way-Liste",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/564726",
      relatedTitle: "Dazu bauen",
      related: [
        { href: "/guides/drunken-fist", label: "Drunken Fist" },
        { href: "/guides/builds", label: "Builds" },
        { href: "/guides/martial-arts-weapons", label: "Kampfkünste" },
        { href: "/guides/gauntlets", label: "2.0-Gauntlets" },
      ],
    },
  },
  "mohist-hill": {
    en: {
      checked: "Version 2.0 sect · still the Hidden Mountain hub",
      title: "Where Winds Meet Mohist Hill: Join, Shop, and Gauntlets",
      intro: "Mohist Hill is the construction-and-mechanism sect added with Hidden Mountain. You can browse its shop without joining, which is how most players buy the Version 2.0 Gauntlets. The lived-in mountain city is also the Cloudstair construction hub for Heaven’s Threshold.",
      hero: "/guides/mohist-hill/hero.jpg",
      heroAlt: "Cliffside mechanical city with waterwheels, workshops, and timber walkways",
      videoId: "xQqbepOOLrE",
      videoTitle: "Official Hidden Mountain launch trailer",
      stepsTitle: "Use the sect without getting lost",
      steps: [
        "Reach Hidden Mountain (Level 32 plus Haven Astray on current official copy) so Mohist Hill exists on your client.",
        "Open Sects → Shop → View other sects → Mohist Hill to buy Gauntlets and listed Inner Ways while sectless.",
        "Joining is optional. It is a construction flavour sect, not a required combat class.",
        "Cloudtop Ascent / Cloudstair NPCs sit in Mohist City. A locked Heaven’s Threshold is usually the server bar, not a failed join.",
        "Celestial Seize is the mystic art that powers many Mohist chain and bird puzzles, including Ephemeral Glory.",
      ],
      extraTitle: "What Mohist Hill is for",
      extraItems: [
        { title: "Shop", body: "2.0 Gauntlets and related Inner Ways. Separate from Drunken Fist." },
        { title: "Traversal", body: "Water rails, Cloudstair, and building tools from the 2.1 letter." },
        { title: "Story", body: "Mohist crisis continues in Chapter 4: Bringer of Embers and Heaven’s Threshold." },
      ],
      blockerTitle: "Sect or shop missing",
      fixes: ["Client still on 1.8: Hidden Mountain is not in that build.", "Shop empty: use View other sects.", "Heaven’s Threshold locked: that is Cloudstair, see the dedicated page.", "Bird puzzles stuck: you need Celestial Seize."],
      evidence: "Sect role and Gauntlets naming come from the July 19 official letter. Shop-without-join is the current creator menu route. Cloudstair remains official 2.1.",
      officialLabel: "Into Hidden Mountain letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Version 2.1 connection letter",
      serpUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      relatedTitle: "Mohist routes",
      related: [
        { href: "/guides/gauntlets", label: "Gauntlets shop" },
        { href: "/guides/sects", label: "All sects" },
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/ephemeral-glory", label: "Ephemeral Glory" },
      ],
    },
    vi: {
      checked: "Môn phái 2.0 · hub Hidden Mountain",
      title: "Mohist Hill Where Winds Meet: nhập môn, shop, Gauntlets",
      intro: "Mohist Hill là môn xây dựng/cơ quan của Hidden Mountain. Có thể xem shop khi chưa nhập môn để mua Gauntlets 2.0. Thành trên núi cũng là hub Cloudstair.",
      hero: "/guides/mohist-hill/hero.jpg",
      heroAlt: "Thành cơ quan trên vách núi với bánh xe nước",
      videoId: "xQqbepOOLrE",
      videoTitle: "Trailer Hidden Mountain",
      stepsTitle: "Dùng môn mà không lạc",
      steps: [
        "Vào Hidden Mountain (Lv.32 + Haven Astray trên copy official hiện tại).",
        "Sects → Shop → View other sects → Mohist Hill, mua Gauntlets khi chưa nhập môn.",
        "Nhập môn không bắt buộc.",
        "NPC Cloudstair ở Mohist City. Heaven’s Threshold khóa thường do thanh server.",
        "Celestial Seize chạy nhiều đố xích và chim, gồm Ephemeral Glory.",
      ],
      extraTitle: "Mohist Hill để làm gì",
      extraItems: [
        { title: "Shop", body: "Gauntlets 2.0, khác Drunken Fist." },
        { title: "Di chuyển", body: "Water rails, Cloudstair, công cụ xây 2.1." },
        { title: "Cốt truyện", body: "Khủng hoảng Mohist ở Chapter 4 và Heaven’s Threshold." },
      ],
      blockerTitle: "Không thấy môn / shop",
      fixes: ["Client 1.8 không có Hidden Mountain.", "Shop trống: View other sects.", "Heaven’s Threshold: trang Cloudstair.", "Đố chim: cần Celestial Seize."],
      evidence: "Vai trò môn và Gauntlets từ thư 19/7. Shop không nhập môn từ menu creator.",
      officialLabel: "Thư Hidden Mountain",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Thư 2.1",
      serpUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      relatedTitle: "Tuyến Mohist",
      related: [
        { href: "/guides/gauntlets", label: "Shop Gauntlets" },
        { href: "/guides/sects", label: "Môn phái" },
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/ephemeral-glory", label: "Ephemeral Glory" },
      ],
    },
    de: {
      checked: "Version-2.0-Sekte · Hidden-Mountain-Hub",
      title: "Where Winds Meet Mohist Hill: beitreten, Shop, Gauntlets",
      intro: "Mohist Hill ist die Bau- und Mechanik-Sekte von Hidden Mountain. Der Shop ist ohne Beitritt nutzbar – so kaufen die meisten die 2.0-Gauntlets. Die Bergstadt ist auch der Cloudstair-Hub.",
      hero: "/guides/mohist-hill/hero.jpg",
      heroAlt: "Mechanische Klippenstadt mit Wasserrädern",
      videoId: "xQqbepOOLrE",
      videoTitle: "Offizieller Hidden-Mountain-Trailer",
      stepsTitle: "Sekte nutzen, ohne stecken zu bleiben",
      steps: [
        "Hidden Mountain erreichen (Lv. 32 plus Haven Astray laut aktuellem Official).",
        "Sects → Shop → View other sects → Mohist Hill, Gauntlets auch ohne Sekte kaufen.",
        "Beitritt ist optional.",
        "Cloudstair-NPCs in Mohist City. Locked Heaven’s Threshold ist meist der Serverbalken.",
        "Celestial Seize treibt Ketten- und Vogelrätsel, inklusive Ephemeral Glory.",
      ],
      extraTitle: "Wofür Mohist Hill da ist",
      extraItems: [
        { title: "Shop", body: "2.0-Gauntlets, nicht Drunken Fist." },
        { title: "Traversal", body: "Water Rails, Cloudstair, 2.1-Bauwerkzeuge." },
        { title: "Story", body: "Mohist-Krise in Kapitel 4 und Heaven’s Threshold." },
      ],
      blockerTitle: "Sekte oder Shop fehlt",
      fixes: ["1.8-Client ohne Hidden Mountain.", "Shop leer: View other sects.", "Heaven’s Threshold: Cloudstair-Seite.", "Vogelrätsel: Celestial Seize."],
      evidence: "Sektenrolle und Gauntlets aus dem Brief vom 19. Juli. Shop ohne Beitritt aus aktuellem Creator-Menüpfad.",
      officialLabel: "Hidden-Mountain-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "2.1-Brief",
      serpUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      relatedTitle: "Mohist-Routen",
      related: [
        { href: "/guides/gauntlets", label: "Gauntlets-Shop" },
        { href: "/guides/sects", label: "Sekten" },
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/ephemeral-glory", label: "Ephemeral Glory" },
      ],
    },
  },
  "divinecraft-dungeons": {
    en: {
      checked: "Hub · Qinghe routes plus Hidden Mountain names",
      title: "Where Winds Meet Divinecraft Dungeons: Locations and How They Work",
      intro: "Divinecraft Dungeons are short underground puzzle caverns, not raid bosses. Enter, grab optional chests, reach the final chest, leave with a fixed payout. Mist-Shrouded Prison on this site is the fully illustrated example. Hidden Mountain added Phasecycle, Zenithstride, Zenithmaze, and Dragondive.",
      hero: "/guides/divinecraft-dungeons/hero.jpg",
      heroAlt: "Underground clockwork dungeon with lanterns, gears, and a glowing treasure chest",
      videoId: "so9akUoFTrM",
      videoTitle: "Kaifeng Divinecraft dungeon walkthrough",
      stepsTitle: "How every Divinecraft run works",
      steps: [
        "Find the cave or marked entrance near a landmark. Many Qinghe doors sit at Mercyheart Monastery, Palace of Annals, or Peace Bell Tower.",
        "Bring lightness movement. Traps, disappearing floors, and ropes matter more than a DPS rotation.",
        "Optional chests are extra; the final chest is the clear. You can finish without 100% chests.",
        "Celestial Seize, Cloud Steps, Still Waters, and fire arrows solve a large share of gates.",
        "After Hidden Mountain, add Phasecycle (northwest Hidden Mountain) and Zenithstride / Zenithmaze (Heaven’s Threshold) to the loop.",
      ],
      extraTitle: "Documented Qinghe cluster",
      extraItems: [
        { title: "Coppergold Hollow / Vanishing Steps / Stone Quake", body: "Mercyheart Monastery, Sundara Land. Rising Oscillating Jade and Enlightenment payouts." },
        { title: "Swallowlight", body: "Palace of Annals, Moonveil. Moving platforms can be skipped via the left crouch / rope / elevator side route." },
        { title: "Arrowfire Tongming", body: "Peace Bell Tower. Strong Enlightenment plus Stormveil Disc." },
        { title: "Mist-Shrouded Prison", body: "Kaifeng Mistveil Forest. Full chest loop already lives on this site." },
      ],
      blockerTitle: "Entrance missing or you fell forever",
      fixes: ["Some cave mouths read better at night. Set time to midnight and look seaward of stone spires.", "Heaven’s Threshold dungeons stay locked until Cloudstair completes on your server.", "A spike room is often the path: smash or drop through wood rather than turning back.", "Use the interactive map pins rather than wandering the full cliff."],
      evidence: "Qinghe reward table and Swallowlight skip are from AllThings.How and long-running dungeon videos. Hidden Mountain names are on Game8’s current dungeon index. Chest-by-chest Hidden Mountain routes are on the child pages only when a walkthrough exists.",
      officialLabel: "Official news",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Divinecraft location table",
      serpUrl: "https://allthings.how/where-winds-meet-divinecraft-dungeons-locations-rewards-and-how-they-work/",
      relatedTitle: "Open a dungeon",
      related: [
        { href: "/guides/mist-shrouded-prison", label: "Mist-Shrouded Prison" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/tools/interactive-map", label: "Interactive map" },
      ],
    },
    vi: {
      checked: "Hub · Qinghe và Hidden Mountain",
      title: "Divinecraft Dungeons Where Winds Meet: vị trí và cách chạy",
      intro: "Divinecraft là hang đố ngắn, không phải raid. Vào, lấy rương tùy chọn, rương cuối, ra. Mist-Shrouded Prison trên site là ví dụ đủ ảnh. Hidden Mountain thêm Phasecycle, Zenithstride, Zenithmaze, Dragondive.",
      hero: "/guides/divinecraft-dungeons/hero.jpg",
      heroAlt: "Hang cơ quan dưới lòng đất với rương phát sáng",
      videoId: "so9akUoFTrM",
      videoTitle: "Walkthrough Divinecraft Kaifeng",
      stepsTitle: "Mọi run Divinecraft",
      steps: [
        "Tìm cửa hang gần landmark.",
        "Mang kỹ năng lightness. Bẫy quan trọng hơn DPS.",
        "Rương tùy chọn; rương cuối là clear.",
        "Celestial Seize, Cloud Steps, Still Waters, tên lửa giải nhiều cổng.",
        "Sau Hidden Mountain: Phasecycle tây bắc, Zenithstride / Zenithmaze ở Heaven’s Threshold.",
      ],
      extraTitle: "Cụm Qinghe đã ghi",
      extraItems: [
        { title: "Mercyheart trio", body: "Coppergold, Vanishing Steps, Stone Quake." },
        { title: "Swallowlight", body: "Palace of Annals; có đường dây/elevator tránh platform." },
        { title: "Arrowfire Tongming", body: "Peace Bell Tower." },
        { title: "Mist-Shrouded Prison", body: "Đã có trang đủ rương." },
      ],
      blockerTitle: "Không thấy cửa / rơi mãi",
      fixes: ["Thử nửa đêm với cửa hang.", "Heaven’s Threshold chờ Cloudstair.", "Phòng gai đôi khi là đường đi.", "Dùng pin map."],
      evidence: "Bảng Qinghe từ AllThings.How. Tên Hidden Mountain từ index Game8.",
      officialLabel: "Tin official",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Bảng Divinecraft",
      serpUrl: "https://allthings.how/where-winds-meet-divinecraft-dungeons-locations-rewards-and-how-they-work/",
      relatedTitle: "Mở một dungeon",
      related: [
        { href: "/guides/mist-shrouded-prison", label: "Mist-Shrouded Prison" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/tools/interactive-map", label: "Map" },
      ],
    },
    de: {
      checked: "Hub · Qinghe plus Hidden Mountain",
      title: "Where Winds Meet Divinecraft Dungeons: Orte und Ablauf",
      intro: "Divinecraft sind kurze Puzzle-Kavernen. Rein, optionale Truhen, Finaltruhe, raus. Mist-Shrouded Prison ist das bebilderte Beispiel. Hidden Mountain ergänzt Phasecycle, Zenithstride, Zenithmaze und Dragondive.",
      hero: "/guides/divinecraft-dungeons/hero.jpg",
      heroAlt: "Unterirdisches Uhrwerk-Dungeon mit Truhe",
      videoId: "so9akUoFTrM",
      videoTitle: "Kaifeng-Divinecraft-Walkthrough",
      stepsTitle: "So läuft jeder Run",
      steps: [
        "Höhleneingang an einem Landmark finden.",
        "Leichtkörper mitbringen. Fallen schlagen DPS.",
        "Optionale Truhen; die letzte Truhe ist der Clear.",
        "Celestial Seize, Cloud Steps, Still Waters, Feuerpfeile öffnen viele Tore.",
        "Danach Phasecycle (Nordwest-Hidden-Mountain) und Zenithstride / Zenithmaze (Heaven’s Threshold).",
      ],
      extraTitle: "Dokumentiertes Qinghe-Cluster",
      extraItems: [
        { title: "Mercyheart-Trio", body: "Coppergold, Vanishing Steps, Stone Quake." },
        { title: "Swallowlight", body: "Palace of Annals; Seil/Aufzug umgeht Plattformen." },
        { title: "Arrowfire Tongming", body: "Peace Bell Tower." },
        { title: "Mist-Shrouded Prison", body: "Volle Truhenroute bereits auf der Site." },
      ],
      blockerTitle: "Eingang weg oder Endlosfall",
      fixes: ["Nachts suchen.", "Heaven’s Threshold wartet auf Cloudstair.", "Stachelraum oft der Weg nach unten.", "Map-Pins nutzen."],
      evidence: "Qinghe-Tabelle nach AllThings.How. Hidden-Mountain-Namen nach Game8.",
      officialLabel: "Offizielle News",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Divinecraft-Tabelle",
      serpUrl: "https://allthings.how/where-winds-meet-divinecraft-dungeons-locations-rewards-and-how-they-work/",
      relatedTitle: "Einen Dungeon öffnen",
      related: [
        { href: "/guides/mist-shrouded-prison", label: "Mist-Shrouded Prison" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/tools/interactive-map", label: "Karte" },
      ],
    },
  },
  phasecycle: {
    en: {
      checked: "Hidden Mountain Divinecraft · September 2026",
      title: "Where Winds Meet Phasecycle Dungeon: Location and Chest Route Logic",
      intro: "Phasecycle is the Divinecraft dungeon in northwest Hidden Mountain. Treat it like every other Divinecraft: optional chests, one final chest, movement puzzles. This page pins the region and the loop. It does not invent unverified chest numbers.",
      hero: "/guides/phasecycle/hero.jpg",
      heroAlt: "Clockwork dungeon corridor with hanging lanterns and a treasure chest",
      videoId: "Bm4RQvNab-g",
      videoTitle: "Hidden Mountain chest + Dragondive context (nearby valley)",
      stepsTitle: "Run Phasecycle cleanly",
      steps: [
        "Unlock Hidden Mountain first, then travel to the northwest mountain cluster. Use the interactive map Divinecraft filter.",
        "Enter the marked cave. If the pin is missing, you are probably still on a pre-2.0 client or looking at Qinghe.",
        "Clear optional chests when they sit on the main line. Skip ones that demand a mystic art you do not have yet.",
        "The final chest is the dungeon complete. Turn back only if a side chest is visible from the main path.",
        "If you came for Heaven’s Threshold names, switch to Zenithstride. Phasecycle is the mountain-northwest door, not the cloud palace.",
      ],
      extraTitle: "Bring these mystic arts",
      extraItems: [
        { title: "Celestial Seize", body: "Pulls switches, chains, and out-of-reach chests." },
        { title: "Cloud Steps / Still Waters", body: "Gaps, spike timing, and aimed shots." },
        { title: "Sister dungeons", body: "Dragondive sits near Jadestream Valley. Zenithstride and Zenithmaze sit in Heaven’s Threshold." },
      ],
      blockerTitle: "No entrance",
      fixes: ["Hidden Mountain not unlocked.", "Wrong corner of the map: northwest mountain, not Heaven’s Threshold.", "Server still showing wait-for-development on the high peak — that is Cloudstair, not Phasecycle.", "Filter the interactive map to Divinecraft Dungeon."],
      evidence: "Location comes from Game8’s September 4 dungeon index. The run logic matches every documented Divinecraft. Chest-by-chest coordinates are omitted until a first-party or timestamped walkthrough is checked.",
      officialLabel: "Official 2.1 trail",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Game8 dungeon index",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "More Divinecraft",
      related: [
        { href: "/guides/divinecraft-dungeons", label: "Dungeon hub" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/mist-shrouded-prison", label: "Mist-Shrouded Prison" },
        { href: "/tools/interactive-map", label: "Map" },
      ],
    },
    vi: {
      checked: "Divinecraft Hidden Mountain · 9/2026",
      title: "Phasecycle Where Winds Meet: vị trí và logic rương",
      intro: "Phasecycle nằm tây bắc Hidden Mountain. Chạy như Divinecraft khác: rương tùy chọn, một rương cuối. Không bịa số rương chưa kiểm.",
      hero: "/guides/phasecycle/hero.jpg",
      heroAlt: "Hành lang dungeon cơ quan",
      videoId: "Bm4RQvNab-g",
      videoTitle: "Ngữ cảnh rương Hidden Mountain",
      stepsTitle: "Chạy sạch",
      steps: [
        "Mở Hidden Mountain, tới cụm núi tây bắc. Lọc Divinecraft trên map.",
        "Vào hang. Sai client 1.8 hoặc đang đứng Qinghe thì không có cửa.",
        "Lấy rương trên đường chính, bỏ rương cần mystic chưa có.",
        "Rương cuối là clear.",
        "Thiên cung mây là Zenithstride, không phải Phasecycle.",
      ],
      extraTitle: "Mang mystic",
      extraItems: [
        { title: "Celestial Seize", body: "Kéo xích và rương." },
        { title: "Cloud Steps / Still Waters", body: "Khe và bẫy." },
        { title: "Dungeon chị em", body: "Dragondive, Zenithstride, Zenithmaze." },
      ],
      blockerTitle: "Không có cửa",
      fixes: ["Chưa Hidden Mountain.", "Nhầm Heaven’s Threshold.", "Wait-for-development là Cloudstair.", "Lọc map Divinecraft."],
      evidence: "Vị trí theo index Game8 4/9. Logic run theo Divinecraft đã ghi.",
      officialLabel: "Trail 2.1",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Index dungeon",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "Divinecraft khác",
      related: [
        { href: "/guides/divinecraft-dungeons", label: "Hub" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/mist-shrouded-prison", label: "Prison" },
        { href: "/tools/interactive-map", label: "Map" },
      ],
    },
    de: {
      checked: "Hidden-Mountain-Divinecraft · September 2026",
      title: "Where Winds Meet Phasecycle: Ort und Truhenlogik",
      intro: "Phasecycle liegt im Nordwesten von Hidden Mountain. Wie jedes Divinecraft: optionale Truhen, eine Finaltruhe. Keine erfundenen Truhenzahlen.",
      hero: "/guides/phasecycle/hero.jpg",
      heroAlt: "Uhrwerk-Dungeonkorridor",
      videoId: "Bm4RQvNab-g",
      videoTitle: "Hidden-Mountain-Truhenkontext",
      stepsTitle: "Sauber laufen",
      steps: [
        "Hidden Mountain öffnen, Nordwest-Cluster, Divinecraft-Filter.",
        "Höhle betreten. 1.8 oder Qinghe = keine Tür.",
        "Truhen auf der Hauptlinie, Rest überspringen.",
        "Letzte Truhe = Clear.",
        "Wolkenpalast ist Zenithstride.",
      ],
      extraTitle: "Mystic Arts mitbringen",
      extraItems: [
        { title: "Celestial Seize", body: "Ketten und Truhen ziehen." },
        { title: "Cloud Steps / Still Waters", body: "Lücken und Fallen." },
        { title: "Nachbar-Dungeons", body: "Dragondive, Zenithstride, Zenithmaze." },
      ],
      blockerTitle: "Kein Eingang",
      fixes: ["Hidden Mountain fehlt.", "Falsche Ecke, nicht Heaven’s Threshold.", "Wait-for-development = Cloudstair.", "Karte auf Divinecraft filtern."],
      evidence: "Ort nach Game8-Index vom 4. September. Run-Logik wie dokumentierte Divinecraft.",
      officialLabel: "2.1-Trail",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/903update.html",
      serpLabel: "Dungeon-Index",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "Mehr Divinecraft",
      related: [
        { href: "/guides/divinecraft-dungeons", label: "Hub" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/mist-shrouded-prison", label: "Prison" },
        { href: "/tools/interactive-map", label: "Karte" },
      ],
    },
  },
  zenithstride: {
    en: {
      checked: "Heaven’s Threshold Divinecraft · September 2026",
      title: "Where Winds Meet Zenithstride and Zenithmaze: Heaven’s Threshold Dungeons",
      intro: "Zenithstride and Zenithmaze are the Divinecraft pair inside Heaven’s Threshold. If the high map still says wait for development, finish Cloudstair first. These are chest caverns in the cloud layer, not the northwest Phasecycle door.",
      hero: "/guides/zenithstride/hero.jpg",
      heroAlt: "Stone stairway into a cloud palace with banners and bronze birds",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Official Heaven’s Threshold trailer",
      stepsTitle: "Reach the cloud dungeons",
      steps: [
        "Complete Cloudtop Ascent / Cloudstair on your server so Heaven’s Threshold exists.",
        "Travel into Heaven’s Threshold and filter the map for Divinecraft Dungeon. Zenithstride and Zenithmaze are separate doors in the same high region.",
        "Run them as standard Divinecraft: optional chests, final chest, lightness movement.",
        "Chasing the Sky flight courses also start from Mirkvale, Stellabed Rocks, and Goldflow Slope in this region. Do not confuse those with dungeon entrances.",
        "If you still need Qinghe practice, Swallowlight and Arrowfire Tongming teach the same trap language at a lower height.",
      ],
      extraTitle: "Same region, different intents",
      extraItems: [
        { title: "Zenithstride / Zenithmaze", body: "Divinecraft chest caverns." },
        { title: "Mirkvale", body: "Campaign quest plus Bell Toller, not a Divinecraft." },
        { title: "Evershift Labyrinth", body: "Jianghu Legacy rotating puzzle under Divinecraft Pavilion." },
      ],
      blockerTitle: "High map still locked",
      fixes: ["Cloudstair server bar incomplete.", "Personal Work Merit is not the gate; shared construction is.", "Looking at Phasecycle in the foothills by mistake.", "Need Celestial Seize for interior chain gates."],
      evidence: "Names and Heaven’s Threshold placement are from Game8’s September 4 dungeon updates. Unlock still follows the official Cloudstair letter. Interior chest coordinates are not guessed.",
      officialLabel: "Cloudstair developer letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Dungeon index",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "Heaven’s Threshold cluster",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair unlock" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/mirkvale", label: "Mirkvale" },
        { href: "/guides/evershift-labyrinth", label: "Evershift Labyrinth" },
      ],
    },
    vi: {
      checked: "Divinecraft Heaven’s Threshold · 9/2026",
      title: "Zenithstride và Zenithmaze Where Winds Meet",
      intro: "Hai Divinecraft trong Heaven’s Threshold. Map cao còn wait-for-development thì làm Cloudstair trước.",
      hero: "/guides/zenithstride/hero.jpg",
      heroAlt: "Bậc đá lên thành mây",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Trailer Heaven’s Threshold",
      stepsTitle: "Tới dungeon mây",
      steps: [
        "Xong Cloudstair toàn server.",
        "Vào Heaven’s Threshold, lọc Divinecraft. Hai cửa riêng.",
        "Chạy như Divinecraft thường.",
        "Chasing the Sky là mini-game bay, không phải cửa dungeon.",
        "Cần luyện Qinghe: Swallowlight / Arrowfire.",
      ],
      extraTitle: "Cùng vùng, khác intent",
      extraItems: [
        { title: "Zenithstride / Zenithmaze", body: "Hang rương Divinecraft." },
        { title: "Mirkvale", body: "Campaign + Bell Toller." },
        { title: "Evershift Labyrinth", body: "Jianghu Legacy khối xoay." },
      ],
      blockerTitle: "Map cao vẫn khóa",
      fixes: ["Thanh Cloudstair chưa xong.", "Work Merit cá nhân không mở cổng.", "Nhầm Phasecycle chân núi.", "Thiếu Celestial Seize."],
      evidence: "Tên và vùng từ Game8 4/9. Mở khóa theo thư Cloudstair.",
      officialLabel: "Thư Cloudstair",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Index dungeon",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "Cụm Heaven’s Threshold",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/mirkvale", label: "Mirkvale" },
        { href: "/guides/evershift-labyrinth", label: "Labyrinth" },
      ],
    },
    de: {
      checked: "Heaven’s-Threshold-Divinecraft · September 2026",
      title: "Where Winds Meet Zenithstride und Zenithmaze",
      intro: "Das Divinecraft-Paar in Heaven’s Threshold. Steht die Hochkarte auf wait for development, zuerst Cloudstair.",
      hero: "/guides/zenithstride/hero.jpg",
      heroAlt: "Steintreppe in einen Wolkenpalast",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Offizieller Heaven’s-Threshold-Trailer",
      stepsTitle: "Zu den Wolken-Dungeons",
      steps: [
        "Cloudstair serverseitig fertig.",
        "Heaven’s Threshold, Filter Divinecraft. Zwei getrennte Türen.",
        "Standard-Divinecraft laufen.",
        "Chasing the Sky ist Flugkurs, kein Dungeoneingang.",
        "Qinghe-Übung: Swallowlight / Arrowfire.",
      ],
      extraTitle: "Gleiche Region, andere Absicht",
      extraItems: [
        { title: "Zenithstride / Zenithmaze", body: "Divinecraft-Truhen." },
        { title: "Mirkvale", body: "Kampagne plus Bell Toller." },
        { title: "Evershift Labyrinth", body: "Jianghu-Legacy-Drehblock." },
      ],
      blockerTitle: "Hochkarte gesperrt",
      fixes: ["Cloudstair-Balken.", "Work Merit reicht nicht.", "Phasecycle in den Vorbergen verwechselt.", "Celestial Seize fehlt."],
      evidence: "Namen nach Game8 vom 4. September. Unlock nach Cloudstair-Brief.",
      officialLabel: "Cloudstair-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Dungeon-Index",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/565898",
      relatedTitle: "Heaven’s-Threshold-Cluster",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/phasecycle", label: "Phasecycle" },
        { href: "/guides/mirkvale", label: "Mirkvale" },
        { href: "/guides/evershift-labyrinth", label: "Labyrinth" },
      ],
    },
  },
  "ephemeral-glory": {
    en: {
      checked: "Hidden Mountain Jianghu Legacy · bird puzzles",
      title: "Where Winds Meet Ephemeral Glory: Mechanical Bird Puzzle Guide",
      intro: "Ephemeral Glory is the Lost Chapter that teaches Mohist chain logic. Start at Chen Hour, speak with Chen Shezhi, then power chain posts so the small birds match the large statue poses. Celestial Seize is required.",
      hero: "/guides/ephemeral-glory/hero.jpg",
      heroAlt: "Mechanical bronze birds linked by glowing chains inside a Mohist hall",
      videoId: "u882bd11kSw",
      videoTitle: "Full Ephemeral Glory Lost Chapter walkthrough",
      stepsTitle: "Solve the bird rooms",
      steps: [
        "Wait until Chen Hour, speak with Chen Shezhi at the Ephemeral Glory start, cross the broken bridge, then take the zipline to puzzle 1.",
        "Puzzle 1: match the large bird pose, Celestial Seize the chain onto the matching small bird, door opens.",
        "Puzzle 2: two small birds must move in sync with the statues. Connect chains so both animate together, then rooftop to the next room.",
        "Puzzle 3: two waterwheels. Power each chain post from its wheel, then feed the second chain into the nearby bird. Pull the lever after both birds wake.",
        "Puzzle 4: read the two stationary statues and copy their poses with the room’s chain posts.",
        "Puzzle 5: on the circular platform, rotate counterclockwise twice, connect birds, stand in the centre to ride the lift to Mohist Hall. Speak with Chen and strike the bell.",
      ],
      extraTitle: "Core machine rule",
      extraItems: [
        { title: "A chain post has two hooks", body: "One hook must touch a power source (wheel, live post, or live bird). The second hook then becomes the output." },
        { title: "Large statues are the answer key", body: "Do not power random birds. Copy the pose of the master statue in that room." },
      ],
      blockerTitle: "Door stays shut",
      fixes: ["No Celestial Seize: finish Foul Play first.", "Wrong hour: wait for Chen Hour.", "Only one bird powered in puzzle 3: both waterwheels are required.", "Puzzle 5 lift dead: rotate the platform twice before connecting.", "Later wait-for-development is Cloudstair, not this quest."],
      evidence: "Start hour, Chen Shezhi, and the five-room chain sequence follow AltChar’s Hidden Mountain bird-puzzle guide. Celestial Seize requirement matches the mystic-art list.",
      officialLabel: "Hidden Mountain letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Bird puzzle walkthrough",
      serpUrl: "https://www.altchar.com/guides/how-to-solve-every-ephemeral-glory-bird-puzzle-in-where-winds-meet-hidden-mountain-aI0Vy5Z93jEv",
      relatedTitle: "Mohist puzzle cluster",
      related: [
        { href: "/guides/mystic-arts", label: "Celestial Seize" },
        { href: "/guides/evershift-labyrinth", label: "Evershift Labyrinth" },
        { href: "/guides/mohist-hill", label: "Mohist Hill" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    vi: {
      checked: "Jianghu Legacy Hidden Mountain · đố chim",
      title: "Ephemeral Glory Where Winds Meet: đố chim cơ quan",
      intro: "Lost Chapter dạy logic xích Mohist. Chen Hour, nói Chen Shezhi, cấp điện cho chim nhỏ khớp tượng lớn. Cần Celestial Seize.",
      hero: "/guides/ephemeral-glory/hero.jpg",
      heroAlt: "Chim đồng cơ quan nối xích phát sáng",
      videoId: "u882bd11kSw",
      videoTitle: "Walkthrough full Ephemeral Glory",
      stepsTitle: "Giải từng phòng",
      steps: [
        "Đợi Chen Hour, nói Chen Shezhi, qua cầu gãy, zipline tới đố 1.",
        "Đố 1: khớp tư thế tượng lớn, Seize xích vào chim nhỏ.",
        "Đố 2: hai chim nhỏ chuyển động đồng bộ.",
        "Đố 3: hai bánh xe nước, mỗi bên một chim.",
        "Đố 4: chép hai tượng đứng yên.",
        "Đố 5: xoay platform ngược kim hai lần, đứng giữa lên Mohist Hall, nói Chen, đánh chuông.",
      ],
      extraTitle: "Luật máy",
      extraItems: [
        { title: "Hai móc xích", body: "Một móc vào nguồn, móc còn lại là output." },
        { title: "Tượng lớn là đáp án", body: "Đừng cấp điện chim ngẫu nhiên." },
      ],
      blockerTitle: "Cửa không mở",
      fixes: ["Thiếu Celestial Seize.", "Sai giờ Chen.", "Đố 3 thiếu một bánh xe.", "Đố 5 chưa xoay hai lần.", "Wait-for-development là Cloudstair."],
      evidence: "Theo AltChar. Celestial Seize theo bảng mystic.",
      officialLabel: "Thư Hidden Mountain",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Walkthrough chim",
      serpUrl: "https://www.altchar.com/guides/how-to-solve-every-ephemeral-glory-bird-puzzle-in-where-winds-meet-hidden-mountain-aI0Vy5Z93jEv",
      relatedTitle: "Cụm đố Mohist",
      related: [
        { href: "/guides/mystic-arts", label: "Celestial Seize" },
        { href: "/guides/evershift-labyrinth", label: "Labyrinth" },
        { href: "/guides/mohist-hill", label: "Mohist Hill" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    de: {
      checked: "Hidden-Mountain-Jianghu-Legacy · Vogelrätsel",
      title: "Where Winds Meet Ephemeral Glory: mechanische Vogelrätsel",
      intro: "Lost Chapter für Mohist-Kettenlogik. Chen Hour, Chen Shezhi, kleine Vögel an große Statuen anpassen. Celestial Seize ist Pflicht.",
      hero: "/guides/ephemeral-glory/hero.jpg",
      heroAlt: "Mechanische Bronzevögel mit leuchtenden Ketten",
      videoId: "u882bd11kSw",
      videoTitle: "Kompletter Ephemeral-Glory-Walkthrough",
      stepsTitle: "Die Vogelräume",
      steps: [
        "Chen Hour abwarten, Chen Shezhi sprechen, Brücke, Zipline zu Puzzle 1.",
        "Puzzle 1: Pose der großen Statue, Kette an den passenden kleinen Vogel.",
        "Puzzle 2: zwei kleine Vögel synchron.",
        "Puzzle 3: zwei Wasserräder, beide Vögel.",
        "Puzzle 4: zwei ruhende Statuen kopieren.",
        "Puzzle 5: Plattform zweimal gegen den Uhrzeigersinn, Mitte stehen, Lift zur Mohist Hall, Glocke.",
      ],
      extraTitle: "Maschinenregel",
      extraItems: [
        { title: "Zwei Haken", body: "Ein Haken an die Quelle, der zweite ist Output." },
        { title: "Große Statuen sind der Schlüssel", body: "Keine Zufallsvögel speisen." },
      ],
      blockerTitle: "Tür bleibt zu",
      fixes: ["Kein Celestial Seize.", "Falsche Stunde.", "Puzzle 3: beide Räder.", "Puzzle 5: zweimal drehen.", "Wait-for-development = Cloudstair."],
      evidence: "Start und Fünf-Raum-Folge nach AltChar. Celestial Seize nach der Mystic-Liste.",
      officialLabel: "Hidden-Mountain-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/719devletter.html",
      serpLabel: "Vogel-Walkthrough",
      serpUrl: "https://www.altchar.com/guides/how-to-solve-every-ephemeral-glory-bird-puzzle-in-where-winds-meet-hidden-mountain-aI0Vy5Z93jEv",
      relatedTitle: "Mohist-Puzzle",
      related: [
        { href: "/guides/mystic-arts", label: "Celestial Seize" },
        { href: "/guides/evershift-labyrinth", label: "Labyrinth" },
        { href: "/guides/mohist-hill", label: "Mohist Hill" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
  },
  mirkvale: {
    en: {
      checked: "Heaven’s Threshold campaign · after Cloudstair",
      title: "Where Winds Meet Mirkvale Walkthrough: Unlock and Bell Toller",
      intro: "Mirkvale is the Hidden Mountain campaign in the jagged gorge west of Heaven’s Threshold. It opens with the rest of the high map after Cloudstair, not from a Qinghe board. The boss inside is Bell Toller.",
      hero: "/guides/mirkvale/hero.jpg",
      heroAlt: "Misty mountain gorge with hanging paths, used for the Mirkvale campaign approach",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Official Heaven’s Threshold trailer",
      stepsTitle: "Start Mirkvale",
      steps: [
        "Finish Cloudtop Ascent so Heaven’s Threshold is actually on your map.",
        "Track the campaign pin west of Heaven’s Threshold in the northern Hidden Mountain gorge.",
        "Follow the in-game objectives through the gorge. Treat hanging paths and bells as the traversal language, not optional scenery.",
        "Prepare a deflect-friendly pair for Bell Toller at the campaign fight. Bring a revive companion if you are learning the timing.",
        "Clear, then use the same region for Chasing the Sky courses and the Zenithstride Divinecraft doors.",
      ],
      extraTitle: "Rewards worth the pin",
      extraItems: [
        { title: "Inner Way Tome - Soaring High", body: "Listed on current Game8 campaign rewards along with Hidden Mountain Exploration, Echo Jade, and a large EXP / coin bundle." },
        { title: "Not a Divinecraft", body: "Chest caverns in this altitude are Zenithstride / Zenithmaze. Mirkvale is the story campaign." },
      ],
      blockerTitle: "Pin missing",
      fixes: ["Cloudstair not finished on this server.", "Standing in Mohist City looking down instead of west of Heaven’s Threshold.", "Campaign still grey: leave co-op and retry in your world.", "Confusing Chasing the Sky start points with the campaign door."],
      evidence: "Unlock placement, Bell Toller, and the reward line follow Game8’s August 24 Mirkvale page. Server gate remains the official Cloudstair letter.",
      officialLabel: "Cloudstair letter",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Mirkvale walkthrough",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/616582",
      relatedTitle: "Same mountain",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/bosses", label: "Boss guides" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    vi: {
      checked: "Campaign Heaven’s Threshold · sau Cloudstair",
      title: "Mirkvale Where Winds Meet: mở khóa và Bell Toller",
      intro: "Campaign khe núi phía tây Heaven’s Threshold. Mở cùng map cao sau Cloudstair. Boss là Bell Toller.",
      hero: "/guides/mirkvale/hero.jpg",
      heroAlt: "Khe núi sương mù",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Trailer Heaven’s Threshold",
      stepsTitle: "Bắt đầu Mirkvale",
      steps: [
        "Xong Cloudstair.",
        "Pin campaign phía tây Heaven’s Threshold, khe bắc Hidden Mountain.",
        "Theo objective. Chuông và đường treo là ngôn ngữ di chuyển.",
        "Chuẩn bị cặp deflect cho Bell Toller.",
        "Sau đó làm Chasing the Sky và Zenithstride trong cùng vùng.",
      ],
      extraTitle: "Phần thưởng",
      extraItems: [
        { title: "Inner Way Tome - Soaring High", body: "Theo Game8 cùng Exploration, Echo Jade, EXP/coin." },
        { title: "Không phải Divinecraft", body: "Hang rương là Zenithstride / Zenithmaze." },
      ],
      blockerTitle: "Không thấy pin",
      fixes: ["Cloudstair chưa xong.", "Đứng nhầm Mohist City.", "Thử solo world.", "Nhầm điểm Chasing the Sky."],
      evidence: "Vị trí, Bell Toller, thưởng theo Game8 24/8.",
      officialLabel: "Thư Cloudstair",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Walkthrough Mirkvale",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/616582",
      relatedTitle: "Cùng núi",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/bosses", label: "Boss" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
    de: {
      checked: "Heaven’s-Threshold-Kampagne · nach Cloudstair",
      title: "Where Winds Meet Mirkvale: Freischalten und Bell Toller",
      intro: "Kampagne in der Schlucht westlich von Heaven’s Threshold. Öffnet mit der Hochkarte nach Cloudstair. Boss ist Bell Toller.",
      hero: "/guides/mirkvale/hero.jpg",
      heroAlt: "Neblige Bergschlucht",
      videoId: "8MHyHYcJzJo",
      videoTitle: "Offizieller Heaven’s-Threshold-Trailer",
      stepsTitle: "Mirkvale starten",
      steps: [
        "Cloudstair fertig.",
        "Kampagnenpin westlich von Heaven’s Threshold in der nördlichen Schlucht.",
        "Objektiven folgen. Glocken und Hängebfade sind Traversal.",
        "Deflect-fähiges Pair für Bell Toller.",
        "Danach Chasing the Sky und Zenithstride in derselben Region.",
      ],
      extraTitle: "Rewards",
      extraItems: [
        { title: "Inner Way Tome - Soaring High", body: "Laut Game8 plus Exploration, Echo Jade, EXP/Coins." },
        { title: "Kein Divinecraft", body: "Truhenkavernen sind Zenithstride / Zenithmaze." },
      ],
      blockerTitle: "Kein Pin",
      fixes: ["Cloudstair fehlt.", "In Mohist City statt westlich der Schwelle.", "Solo-Welt versuchen.", "Chasing-the-Sky-Start verwechselt."],
      evidence: "Ort, Bell Toller und Rewards nach Game8 vom 24. August.",
      officialLabel: "Cloudstair-Brief",
      officialUrl: "https://www.wherewindsmeetgame.com/news/official/821devletter.html",
      serpLabel: "Mirkvale-Walkthrough",
      serpUrl: "https://game8.co/games/Where-Winds-Meet/archives/616582",
      relatedTitle: "Derselbe Berg",
      related: [
        { href: "/guides/heavens-threshold-cloudstair", label: "Cloudstair" },
        { href: "/guides/zenithstride", label: "Zenithstride" },
        { href: "/guides/bosses", label: "Bosse" },
        { href: "/guides/hidden-mountain", label: "Hidden Mountain" },
      ],
    },
  },
};

export default function IntentGuidePage({
  language,
  kind,
}: {
  language: IntentGuideLanguage;
  kind: IntentGuideKind;
}) {
  const page = guides[kind][language];
  const base = prefix[language];
  const poster = page.videoId ? `https://i.ytimg.com/vi/${page.videoId}/hqdefault.jpg` : undefined;

  return (
    <article className="min-h-screen space-y-10 bg-ink-wash pb-20">
      <HomeHubBacklink language={language} />
      <header className="overflow-hidden rounded-3xl border border-violet-400/30 bg-slate-950/85 shadow-2xl">
        <div className="relative min-h-[240px] sm:min-h-[320px]">
          <CdnImage src={page.hero} alt={page.heroAlt} fill className="object-cover" priority />
          <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/55 to-slate-950/20" />
          <div className="relative z-10 max-w-4xl p-6 sm:p-10">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-200">{page.checked}</p>
            <h1 className="mt-3 text-balance text-3xl font-bold text-slate-50 sm:text-5xl">{page.title}</h1>
            <p className="mt-5 max-w-3xl text-base leading-7 text-slate-200 sm:text-lg">{page.intro}</p>
          </div>
        </div>
      </header>

      <section className="grid gap-7 lg:grid-cols-[1.05fr_0.95fr] lg:items-start">
        <div>
          <h2 className="text-3xl font-bold text-slate-50">{page.stepsTitle}</h2>
          <ol className="mt-5 space-y-3">
            {page.steps.map((step, index) => (
              <li key={step} className="flex gap-4 rounded-2xl border border-slate-800 bg-slate-950/75 p-4 text-sm leading-6 text-slate-300">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-violet-500/20 font-bold text-violet-200">{index + 1}</span>
                <span>{step}</span>
              </li>
            ))}
          </ol>
        </div>
        {page.videoId ? (
          <div>
            <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-emerald-300">{page.videoTitle}</p>
            <LiteYouTubeEmbed
              videoId={page.videoId}
              title={page.videoTitle || page.title}
              poster={poster}
              analytics={{ eventName: "guide_video_play", params: { guide: kind } }}
            />
          </div>
        ) : null}
      </section>

      {page.extraTitle && page.extraItems ? (
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-slate-50">{page.extraTitle}</h2>
          <div className="grid gap-4 md:grid-cols-2">
            {page.extraItems.map((item) => (
              <div key={item.title} className="rounded-2xl border border-slate-800 bg-slate-950/75 p-5">
                <h3 className="font-semibold text-sky-100">{item.title}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-300">{item.body}</p>
              </div>
            ))}
          </div>
        </section>
      ) : null}

      <section className="rounded-3xl border border-amber-400/30 bg-amber-500/10 p-6 sm:p-8">
        <h2 className="text-2xl font-bold text-slate-50">{page.blockerTitle}</h2>
        <ul className="mt-4 grid gap-3 md:grid-cols-2">
          {page.fixes.map((fix) => (
            <li key={fix} className="rounded-xl border border-amber-300/20 bg-slate-950/50 p-4 text-sm leading-6 text-slate-200">• {fix}</li>
          ))}
        </ul>
      </section>

      <aside className="rounded-3xl border border-slate-700 bg-slate-950/75 p-6">
        <h2 className="font-semibold text-slate-100">Sources</h2>
        <p className="mt-2 text-sm leading-6 text-slate-300">{page.evidence}</p>
        <div className="mt-4 flex flex-wrap gap-2">
          <a href={page.officialUrl} target="_blank" rel="noreferrer" className="rounded-full border border-sky-400/50 px-3 py-1 text-xs font-semibold text-sky-200">{page.officialLabel} ↗</a>
          <a href={page.serpUrl} target="_blank" rel="noreferrer" className="rounded-full border border-slate-600 px-3 py-1 text-xs font-semibold text-slate-200">{page.serpLabel} ↗</a>
        </div>
      </aside>

      <nav className="rounded-3xl border border-emerald-400/20 bg-emerald-500/10 p-6">
        <h2 className="font-semibold text-emerald-100">{page.relatedTitle}</h2>
        <div className="mt-4 flex flex-wrap gap-3">
          {page.related.map((item) => (
            <Link key={item.href} href={`${base}${item.href}`} className="rounded-full border border-emerald-300/40 px-4 py-2 text-sm font-semibold text-emerald-100">
              {item.label} →
            </Link>
          ))}
        </div>
      </nav>
    </article>
  );
}
